// ReSharper disable once CppMissingIncludeGuard

#undef GROUP_ID
#undef GROUP_NAME
#define GROUP_ID 192
#define GROUP_NAME "animalCutsceneGroupDescriptor"
DEFINE_NAMED_STATE(80, "animalCutsceneDoneUberState", SerializedBooleanUberState, false)

#undef GROUP_ID
#undef GROUP_NAME
#define GROUP_ID 195
#define GROUP_NAME "kwoloksGroupDescriptor"
DEFINE_NAMED_STATE(56127, "leafPileB", SerializedBooleanUberState, false)

#undef GROUP_ID
#undef GROUP_NAME
#define GROUP_ID 229
#define GROUP_NAME "_riverlandsGroup"
DEFINE_NAMED_STATE(2, "riverlands_blueFlameDoorBOpen", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(27, "riverlands_pedestalOBurning", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(30, "riverlands_pedestalFBurning", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(35, "riverlands_blueFlameDoorAOpen", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(49, "riverlands_blueFlameDoorFOpen", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(52, "riverlands_pedestalEBurning", SerializedBooleanUberState, true)
DEFINE_NAMED_STATE(62, "riverlands_pedestalABurning", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(66, "riverlands_pedestalIBurning", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(71, "riverlands_pedestalNBurning", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(76, "riverlands_blueFlameDoorEOpen", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(108, "riverlands_pedestalGBurning", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(119, "riverlands_pedestalMBurning", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(129, "riverlands_pedestalCBurning", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(174, "riverlands_pedestalKBurning", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(185, "riverlands_blueFlameDoorCOpen", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(210, "riverlands_pedestalHBurning", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(222, "riverlands_pedestalJBurning", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(226, "riverlands_blueFlameDoorDOpen", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(231, "riverlands_pedestalDBurning", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(233, "riverlands_pedestalBBurning", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(237, "riverlands_pedestalLBurning", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(41675, "savePedestalUberState", SavePedestalUberState, false)

#undef GROUP_ID
#undef GROUP_NAME
#define GROUP_ID 937
#define GROUP_NAME "kwolokGroupDescriptor"
DEFINE_NAMED_STATE(59, "isKwolokMissing", ConditionUberState, false)
DEFINE_STATE(109, SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(749, "watermillDoor", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(1038, "eyesPlacedIntoStatue", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(1174, "cavernGLeverAndDoor", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(2463, "halfHealthCell", SerializedBooleanUberState, false)
DEFINE_STATE(2538, SerializedBooleanUberState, false)  // smallExpOrbPlaceholder
DEFINE_NAMED_STATE(4057, "ravineToadTop04", SerializedBooleanUberState, false)
DEFINE_STATE(5281, SavePedestalUberState, false)  // savePedestal
DEFINE_NAMED_STATE(5568, "xpOrbB", SerializedBooleanUberState, false)
DEFINE_STATE(5668, SerializedBooleanUberState, false)  // energyContainerA
DEFINE_NAMED_STATE(6040, "frogUpperMainRoomBottom", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(6703, "orePickup", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(6778, "mokiGateOpened", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(7119, "drillableWallKwolokF", SerializedBooleanUberState, false)
DEFINE_STATE(7153, SerializedBooleanUberState, false)  // mediumExpA
DEFINE_NAMED_STATE(7270, "raisableBouncePad", BooleanUberState, false)
DEFINE_NAMED_STATE(7941, "ravineToadTop01", SerializedBooleanUberState, false)
DEFINE_STATE(8518, SerializedBooleanUberState, false)  // energyHalfCell
DEFINE_NAMED_STATE(9420, "frogCavernFPuzzleLeftNonSerializable", ByteUberState, 0)
DEFINE_NAMED_STATE(10071, "kwolokNpcState", SerializedIntUberState, 0)
DEFINE_STATE(10140, SerializedBooleanUberState, false)  // secretWallA
DEFINE_NAMED_STATE(10729, "gromOreA", SerializedBooleanUberState, false)
DEFINE_STATE(10877, SerializedBooleanUberState, false)  // smallExpOrbPlaceholder
DEFINE_STATE(11430, SerializedBooleanUberState, false)  // mediumExpA
DEFINE_NAMED_STATE(11610, "bombableWallAkwoloksCavernEa", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(11779, "interactedWithTokkCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(11846, "orePickupB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(12458, "drillableWallKwolokH", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(12557, "frogTongueB", SerializedByteUberState, 255)
DEFINE_NAMED_STATE(13273, "stepsRisen", SerializedBooleanUberState, false)
DEFINE_STATE(13413, SerializedBooleanUberState, false)  // xpOrbA
DEFINE_NAMED_STATE(13557, "retractTongue", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(14026, "frogTongueE", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(14501, "healthPlantTimer", SerializedFloatUberState, 0.0)
DEFINE_NAMED_STATE(15130, "healthPlant", SerializedFloatUberState, 0.0)
DEFINE_STATE(15993, SerializedBooleanUberState, false)  // smallExpA
DEFINE_STATE(16163, SerializedBooleanUberState, false)  // smallExpOrbPlaceholder
DEFINE_NAMED_STATE(16658, "mapIconBashTreeVisibleCondition", ConditionUberState, true)
DEFINE_STATE(17761, SerializedBooleanUberState, false)  // energyContainerA
DEFINE_NAMED_STATE(18035, "temp_WispQuestStandIn", SerializedBooleanUberState, false)
DEFINE_STATE(18103, SerializedBooleanUberState, false)  // smallExpA
DEFINE_NAMED_STATE(19495, "frogCavernGPuzzleLeftUp", SerializedByteUberState, 0)
DEFINE_STATE(19529, SerializedBooleanUberState, false)  // mediumExpC
DEFINE_NAMED_STATE(20219, "smallExpB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(20294, "bombableWallAkwoloksCavernE", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(21165, "kwolokCavernsGate", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(22302, "kwolokShrineBreakableWall", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(22419, "leverDoor", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(22716, "pressurePlatePuzzle", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(23486, "lifeCellA", SerializedBooleanUberState, false)
DEFINE_STATE(23772, SerializedBooleanUberState, false)  // energyHalfCell
DEFINE_NAMED_STATE(24039, "spiritShardA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(24175, "energyHalfContainer", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(24510, "frogCavernBRight", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(25413, "spiritShardMagnet", SerializedBooleanUberState, false)
DEFINE_STATE(26601, SavePedestalUberState, false)  // savePedestal
DEFINE_NAMED_STATE(27481, "drillableWallKwolokC", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(27671, "hornbugWallBroken", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(28504, "frogTop01", SerializedByteUberState, 0)
DEFINE_STATE(30182, SerializedBooleanUberState, false)  // mediumExpB
DEFINE_NAMED_STATE(30594, "ravineBottomTop01", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(30661, "attackableFrogByteUberState", SerializedByteUberState, 0)
DEFINE_STATE(31026, SerializedBooleanUberState, false)  // breakableWallA
DEFINE_STATE(31036, SerializedBooleanUberState, false)  // mediumExpC
DEFINE_NAMED_STATE(31222, "switchTop", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(32165, "door", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(32175, "areaText", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(32452, "drillZoneA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(32948, "kwolokCavernsAttackableToad", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(33763, "keyStoneD", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(33773, "winterForestDoor", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(34340, "ravineToadTop03", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(34343, "airDashHint", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(34396, "leverDoorKwoloksHollowEntrance", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(34516, "haveSpokenToOtters", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(34641, "cleanseWellspringQuestUberState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(34849, "frogTongueA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(36971, "frogCavernFPuzzleRightNonSerializable", ByteUberState, 0)
DEFINE_NAMED_STATE(37823, "drillableWallKwolokI", SerializedBooleanUberState, false)
DEFINE_STATE(37926, SerializedBooleanUberState, false)  // smallExpOrbPlaceholder
DEFINE_NAMED_STATE(37928, "frogBottom03", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(38183, "frogCavernFBottom", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(39338, "drillableWallKwolokD", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(39661, "drillableWallKwolokE", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(39715, "drillableWallKwolokG", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(40042, "secretWallB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(40225, "stompableFloor", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(40298, "mediumExpD", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(40466, "secretWallKwolok", SerializedBooleanUberState, false)
DEFINE_STATE(40657, SerializedBooleanUberState, false)  // smallExpA
DEFINE_NAMED_STATE(40810, "frogCavernGPuzzleRight", SerializedByteUberState, 255)
DEFINE_NAMED_STATE(41587, "frogCavernBLeft", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(42245, "recedingWaterSetup", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(42333, "smallExpOrbPlaceholderB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(42585, "interactedWithTokk", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(44452, "frogCavernELeft", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(44594, "drillableWallKwolok", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(44861, "ravineBottomTop03", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(45349, "stompableFloorB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(45423, "frogUpperMainRoomTopC", SerializedByteUberState, 0)
DEFINE_STATE(45625, SerializedBooleanUberState, false)  // mediumExpA
DEFINE_STATE(45744, SerializedBooleanUberState, false)  // mediumExpB
DEFINE_STATE(45811, SerializedBooleanUberState, false)  // secretWallA
DEFINE_STATE(45987, SerializedBooleanUberState, false)  // mediumExpA
DEFINE_NAMED_STATE(46836, "shouldBouncePadBeRaised", ConditionUberState, false)
DEFINE_NAMED_STATE(47364, "ravineToadTop02", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(47836, "shardTraderState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(48192, "smallExpOrbPlaceholderA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(48534, "hornBugBossState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(49392, "frogBottom02", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(49545, "desertBombableWall", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(49633, "canOpenMokiGate", ConditionUberState, false)
DEFINE_NAMED_STATE(49874, "kwolokCavernsAttackableToadB", SerializedByteUberState, 0)
DEFINE_STATE(50176, SerializedBooleanUberState, false)  // xpOrbA
DEFINE_NAMED_STATE(50357, "drillableWallKwolokB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(50366, "hornBugBossIntroducedState", BooleanUberState, false)
DEFINE_NAMED_STATE(50411, "frogUpperMainRoomTopA", SerializedByteUberState, 0)
DEFINE_STATE(50474, SerializedBooleanUberState, false)  // secretWallA
DEFINE_NAMED_STATE(50615, "energyContainerPlaceholder", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(50803, "frogCavernGPuzzleLeft", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(51234, "frogTongueD", SerializedByteUberState, 0)
DEFINE_STATE(51878, SerializedBooleanUberState, false)  // breakableWallA
DEFINE_NAMED_STATE(51919, "kwolokBossBridgeBroken", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(52065, "mapIconDashTreeVisibleCondition", ConditionUberState, true)
DEFINE_NAMED_STATE(52258, "spiritShardPickupPlaceholder", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(52652, "frogDoor", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(52814, "recedingWaterSetupJordi", SerializedIntUberState, 1)
DEFINE_NAMED_STATE(53122, "hornBugBossDefeatedState", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(53749, "frogCavernERight", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(53969, "bombableWallAkwoloksCavernEb", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(54102, "keyStoneC", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(54236, "brokenWallA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(54318, "risingPedestals", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(55341, "ravineBottomTop02", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(55538, "dashHint", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(56013, "hornBugBossFightPhasePendingCondition", ConditionUberState, true)
DEFINE_NAMED_STATE(56352, "drillableWallKwolokJ", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(56395, "frogCavernGBottom", SerializedByteUberState, 255)
DEFINE_NAMED_STATE(56795, "frogTongueC", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(57028, "leverDoorA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(57262, "mokiDroppedRope", ConditionUberState, false)
DEFINE_NAMED_STATE(57711, "frogTop02", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(57843, "shouldFrogDoorBeOpen", ConditionUberState, false)
DEFINE_STATE(58598, SerializedBooleanUberState, false)  // healthHalfCell
DEFINE_NAMED_STATE(58747, "shootableTargetDoor", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(59288, "frogTop03", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(59404, "ravineBottomTop05", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(59515, "serializedBooleanUberState", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(59850, "doorA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(59920, "switchDoorUberState", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(61099, "ravineBottomTop04", SerializedBooleanUberState, false)
DEFINE_STATE(61460, SerializedBooleanUberState, false)  // mediumExpA
DEFINE_NAMED_STATE(61633, "hornbugIntroArenaUberState", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(61744, "smallExpOrbPlaceholderC", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(61783, "xpOrbC", SerializedBooleanUberState, false)
DEFINE_STATE(61897, SerializedBooleanUberState, false)  // healthHalfCell
DEFINE_NAMED_STATE(62300, "frogBottom04", SerializedByteUberState, 255)
DEFINE_NAMED_STATE(63347, "frogUpperMainRoomTopB", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(63834, "frogCavernBTopRight", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(64003, "entranceStatueOpened", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(64146, "spiritShardPickupPlaceholderB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(64257, "frogBottom01", SerializedByteUberState, 0)
DEFINE_STATE(65195, SerializedBooleanUberState, false)  // mediumExpA

#undef GROUP_ID
#undef GROUP_NAME
#define GROUP_ID 945
#define GROUP_NAME "lagoonStateGroup"
DEFINE_STATE(1370, SavePedestalUberState, false)  // savePedestalUberState
DEFINE_NAMED_STATE(3487, "secretWallA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(3659, "canShowGlideHint", SerializedBooleanUberState, false)
DEFINE_STATE(7031, SerializedBooleanUberState, false)  // mediumExpA
DEFINE_STATE(7465, SerializedBooleanUberState, false)  // breakableWallB
DEFINE_NAMED_STATE(9034, "kwolokBossBridgeBreak", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(9367, "wispSequencePlayedOut", SerializedBooleanUberState, false)
DEFINE_STATE(10682, SerializedBooleanUberState, false)  // mediumExpB
DEFINE_NAMED_STATE(10833, "largeExpC", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(12852, "tentacleKilled", SerializedBooleanUberState, false)
DEFINE_STATE(14530, SerializedBooleanUberState, false)  // mediumExpA
DEFINE_NAMED_STATE(21334, "energyCellA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(23296, "healthPlantA", SerializedFloatUberState, 0.0)
DEFINE_NAMED_STATE(25182, "memoriesPlayed", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(25520, "energyContainerA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(25710, "kwolokBossDroppedRope", ConditionUberState, false)
DEFINE_STATE(28631, SerializedBooleanUberState, false)  // breakableWallA
DEFINE_STATE(32890, SerializedBooleanUberState, false)  // mediumExpA
DEFINE_NAMED_STATE(33930, "displayedGlideHint", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(37243, "lagoonMillTransitionHealthCell", SerializedBooleanUberState, false)
DEFINE_STATE(38319, SerializedBooleanUberState, false)  // mediumExpB
DEFINE_STATE(39004, SerializedBooleanUberState, false)  // breakableWallB
DEFINE_NAMED_STATE(41089, "kwolokBossDefeatedCondition", ConditionUberState, true)
DEFINE_NAMED_STATE(43451, "secretWallB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(49747, "bossReward", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(51273, "canPlayMemories", ConditionUberState, false)
DEFINE_STATE(55795, SerializedBooleanUberState, false)  // breakableWallA
DEFINE_STATE(58183, SavePedestalUberState, false)  // savePedestalUberState
DEFINE_NAMED_STATE(58403, "kwolokBossState", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(58723, "medExpA", SerializedBooleanUberState, false)

#undef GROUP_ID
#undef GROUP_NAME
#define GROUP_ID 3440
#define GROUP_NAME "playerUberStateGroupDescriptor"
DEFINE_NAMED_STATE(1157, "hammerSpeedUpgradeLevel", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(2234, "chargeWeaponsUpgradeLevel", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(5687, "spikeExplosiveUpgradeLevel", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(9670, "spellMeditateUpgradeLevel", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(10233, "waterBreathUpgradeLevel", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(10378, "hasDashCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(10776, "chakramSpinUpgradeLevel", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(10928, "bashSplitUpgradeLevel", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(13998, "playerFirstWeaponMasterPurchase", ConditionUberState, true)
DEFINE_NAMED_STATE(15334, "hasBashCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(16155, "grenadeDamageUpgradeLevel", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(17265, "spellChakramUpgradeLevel", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(18770, "missilesDamageUpgradeLevel", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(20131, "playerPurchasedWeaponMasterUpgrade", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(23948, "dayTimeUberStateCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(24142, "spellSpikeUpgradeLevel", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(26998, "missilesAmountUpgradeLevel", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(27390, "hasRegenerateCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(29503, "bowDamageUpgradeLevel", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(30415, "swordComboUpgradeLevel", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(31259, "healEfficiencyUpgradeLevel", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(33963, "spikeDamageUpgradeLevel", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(34448, "playerWeaponDamageUpgradeLevel", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(38929, "spellSentryUpgradeLevel", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(39658, "swordDamageUpgradeLevel", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(40954, "chakramMagnetUpgradeLevel", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(42913, "chakramDamageUpgradeLevel", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(44044, "hasGlowCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(44414, "hasLeashCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(45149, "hasDigCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(45208, "invisibilityDurationUpgradeLevel", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(46488, "hammerStompUpgradeLevel", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(48877, "sentryAmountUpgradeLevel", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(51302, "disableGoldenSeinCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(53059, "hasGlideCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(53415, "hammerDamageUpgradeLevel", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(54402, "playerOnTandemUberState", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(57376, "sentrySpeedUpgradeLevel", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(58703, "spellBlazeUpgradeLevel", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(61898, "blazeChargeUpgradeLevel", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(62563, "chakramAmountUpgradeLevel", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(64152, "spellHammerUpgradeLevel", SerializedByteUberState, 0)

#undef GROUP_ID
#undef GROUP_NAME
#define GROUP_ID 5377
#define GROUP_NAME "lumaPoolsStateGroup"
DEFINE_NAMED_STATE(628, "largeExpOrbPlaceholderA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(1373, "arenaByteStateSerialized", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(1600, "energyCellFragmentA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(2286, "waterRaised", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(2518, "pullWallLeft", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(3831, "breakableSecretWallA", SerializedBooleanUberState, false)
DEFINE_STATE(4463, SerializedBooleanUberState, false)  // breakableWallB
DEFINE_STATE(6398, SerializedBooleanUberState, false)  // leverAndDoor
DEFINE_STATE(6857, SerializedBooleanUberState, false)  // breakableWallA
DEFINE_NAMED_STATE(7381, "mediumExpOrbPlaceholder", SerializedBooleanUberState, false)
DEFINE_STATE(7540, SerializedBooleanUberState, false)  // xpOrbA
DEFINE_NAMED_STATE(8019, "breakRockDState", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(8294, "trunkState", SerializedBooleanUberState, false)
DEFINE_STATE(8440, SerializedBooleanUberState, false)  // bubbleMakerBlocked
DEFINE_STATE(8451, SerializedBooleanUberState, false)  // breakableWallA
DEFINE_STATE(8939, SerializedBooleanUberState, false)  // expOrb
DEFINE_NAMED_STATE(9812, "expOrbB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(10291, "creepD", SerializedBooleanUberState, false)
DEFINE_STATE(10782, SerializedBooleanUberState, false)  // breakableWallB
DEFINE_NAMED_STATE(11049, "bombableWallA", SerializedBooleanUberState, false)
DEFINE_STATE(12235, SerializedBooleanUberState, false)  // gorlekOreA
DEFINE_NAMED_STATE(12826, "pressurePlateGate", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(13832, "xpOrbD", SerializedBooleanUberState, false)
DEFINE_STATE(14488, SerializedBooleanUberState, false)  // leverAndDoor
DEFINE_STATE(14664, SerializedBooleanUberState, false)  // spiritShard
DEFINE_NAMED_STATE(15383, "drillableWall", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(15402, "dashDoor", SerializedBooleanUberState, false)
DEFINE_STATE(15754, SerializedBooleanUberState, false)  // bubbleMakerUnblockedA
DEFINE_NAMED_STATE(16426, "keystoneB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(16607, "breakRockFState", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(16929, "teleporterUnsubmergedCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(17396, "xpOrbC", SerializedBooleanUberState, false)
DEFINE_STATE(18345, SerializedBooleanUberState, false)  // xpOrbA
DEFINE_NAMED_STATE(19132, "areaText", SerializedBooleanUberState, false)
DEFINE_STATE(19694, SerializedBooleanUberState, false)  // pickupA
DEFINE_NAMED_STATE(21700, "talkedToKwolok", SerializedBooleanUberState, false)
DEFINE_STATE(21860, SerializedBooleanUberState, false)  // xpOrbA
DEFINE_NAMED_STATE(22047, "breakRockEState", SerializedBooleanUberState, false)
DEFINE_STATE(22978, SerializedBooleanUberState, false)  // breakableWallB
DEFINE_NAMED_STATE(24015, "hintZones", SerializedBooleanUberState, false)
DEFINE_STATE(24765, SerializedBooleanUberState, false)  // bubbleMakerUnblockedA
DEFINE_STATE(25391, SerializedBooleanUberState, false)  // xpOrbA
DEFINE_NAMED_STATE(25612, "bridgeState", SerializedBooleanUberState, false)
DEFINE_STATE(25633, SerializedBooleanUberState, false)  // mediumExpOrbPlaceholderB
DEFINE_NAMED_STATE(25775, "kwolokActiveCondition", ConditionUberState, true)
DEFINE_STATE(26170, SerializedBooleanUberState, false)  // breakableWallA
DEFINE_NAMED_STATE(26987, "lagoonDoor", SerializedBooleanUberState, false)
DEFINE_STATE(27204, SerializedBooleanUberState, false)  // xpOrbA
DEFINE_NAMED_STATE(27558, "bombableWall", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(29662, "breakRockCState", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(29911, "loweringWaterState", SerializedBooleanUberState, false)
DEFINE_STATE(30860, SerializedBooleanUberState, false)  // mediumExpOrbPlaceholderB
DEFINE_NAMED_STATE(31093, "treeFallen", SerializedBooleanUberState, false)
DEFINE_STATE(31145, SerializedBooleanUberState, false)  // breakableWallA
DEFINE_STATE(31434, SerializedBooleanUberState, false)  // gorlekOreA
DEFINE_STATE(32210, SerializedBooleanUberState, false)  // bubbleMakerBlocked
DEFINE_NAMED_STATE(32685, "creepB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(32750, "energyContainerA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(33110, "mediumExpOrbPlaceholderC", SerializedBooleanUberState, false)
DEFINE_STATE(33180, SerializedBooleanUberState, false)  // xpOrbA
DEFINE_NAMED_STATE(33730, "breakRockAState", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(34852, "orePickupA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(35023, "playedMokiVignette", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(35091, "keystoneA", SerializedBooleanUberState, false)
DEFINE_STATE(35440, SerializedBooleanUberState, false)  // xpOrbB
DEFINE_STATE(35751, SerializedBooleanUberState, false)  // bubbleMakerUnblockedB
DEFINE_STATE(35971, SerializedBooleanUberState, false)  // expOrb
DEFINE_NAMED_STATE(36511, "breakableFloorA", SerializedBooleanUberState, false)
DEFINE_STATE(38515, SerializedBooleanUberState, false)  // xpOrbA
DEFINE_STATE(40328, SerializedBooleanUberState, false)  // spiritShard
DEFINE_NAMED_STATE(41881, "keystoneD", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(42145, "mainPickup", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(42553, "mediumExpOrbPlaceholderA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(43134, "creepA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(43859, "optionalPickup", SerializedBooleanUberState, false)
DEFINE_STATE(44122, SerializedBooleanUberState, false)  // xpOrbA
DEFINE_NAMED_STATE(44777, "expOrbA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(45765, "switchesActivated", SerializedBooleanUberState, false)
DEFINE_STATE(45774, SerializedBooleanUberState, false)  // healthContainerA
DEFINE_NAMED_STATE(46040, "fallingRockState", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(46926, "keystoneC", SerializedBooleanUberState, false)
DEFINE_STATE(47557, SerializedFloatUberState, 0.0)  // healthPlantA
DEFINE_NAMED_STATE(47621, "keystoneGate", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(49394, "splitPlatformState", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(49826, "pullWallRight", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(50005, "mapIconWaterDashTreeVisibleCondition", ConditionUberState, true)
DEFINE_STATE(52062, SerializedBooleanUberState, false)  // doorState
DEFINE_NAMED_STATE(52133, "breakableLogA", SerializedBooleanUberState, false)
DEFINE_STATE(52791, SerializedBooleanUberState, false)  // xpOrbB
DEFINE_NAMED_STATE(53480, "arenaBByteStateSerialized", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(53532, "bombableWallB", SerializedBooleanUberState, false)
DEFINE_STATE(56199, SerializedBooleanUberState, false)  // spiritShard
DEFINE_STATE(56302, SerializedBooleanUberState, false)  // secretWallA
DEFINE_NAMED_STATE(57334, "creepE", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(57453, "bubbleMakerUnblocked", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(57929, "kwolokChaseDoorState", SerializedBooleanUberState, false)
DEFINE_STATE(58278, SerializedBooleanUberState, false)  // bubbleMakerUnblockedB
DEFINE_STATE(59514, SerializedBooleanUberState, false)  // doorState
DEFINE_STATE(61475, SerializedBooleanUberState, false)  // pickupA
DEFINE_STATE(62180, SerializedBooleanUberState, false)  // xpOrbB
DEFINE_NAMED_STATE(63173, "waterLowered", SerializedBooleanUberState, false)
DEFINE_STATE(63201, SerializedBooleanUberState, false)  // healthContainerA
DEFINE_STATE(63230, SerializedFloatUberState, 0.0)  // healthPlantA
DEFINE_STATE(63513, SerializedBooleanUberState, false)  // doorState
DEFINE_STATE(63922, SerializedBooleanUberState, false)  // secretWallA
DEFINE_NAMED_STATE(64337, "breakableWall", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(64761, "creepC", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(64827, "breakRockBState", SerializedBooleanUberState, false)
DEFINE_STATE(65019, SerializedBooleanUberState, false)  // gorlekOreA
DEFINE_STATE(65413, SerializedBooleanUberState, false)  // breakableWallA

#undef GROUP_ID
#undef GROUP_NAME
#define GROUP_ID 6837
#define GROUP_NAME "testUberStateGroup"
DEFINE_NAMED_STATE(5475, "firePedestalBooleanUberState", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(7403, "kwolokCavernDoor2", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(10235, "desertShortcutWall", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(14776, "arenaWaveState", IntUberState, 0)
DEFINE_NAMED_STATE(19173, "testDoorTwoSlotsBooleanUberState", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(19701, "testShrineUberStateDescriptor", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(31278, "arenaCompletedState", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(31353, "lianaHealLantern", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(37967, "testBreakableWallInt", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(38771, "willowsEndShortcutWall", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(39815, "landOnAndSpawnOrbs", SerializedFloatUberState, 0.0)
DEFINE_NAMED_STATE(40492, "swampShortcutWall", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(44762, "winterForestEnemyDoor", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(47735, "lagoonContactSwitch", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(51086, "watermillShortcutWall", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(54316, "kwolokCavernDoor", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(54999, "testLeverDescriptorDesertC", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(55663, "oneSideBreakableWall", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(60688, "testSecret", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(60823, "testBooleanUberStateDescriptor", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(61358, "testBreakableWallIntB", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(61561, "testSerializedFloatUberState", SerializedFloatUberState, 0.0)
DEFINE_NAMED_STATE(61703, "cordycepsShortcutWall", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(62194, "kwolokCavernsPressurePlate", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(62909, "kwolokCavernsAttackableSwitch", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(63967, "serializedInt", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(64646, "lagoonShortcutWall", SerializedBooleanUberState, false)

#undef GROUP_ID
#undef GROUP_NAME
#define GROUP_ID 7228
#define GROUP_NAME "desertAGroup"
DEFINE_NAMED_STATE(1781, "collectableHDesertA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(2996, "collectableEDesertA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(4034, "secretWall", SerializedBooleanUberState, false)
DEFINE_STATE(8370, SerializedBooleanUberState, false)  // gorlekOre
DEFINE_NAMED_STATE(20282, "keystoneAUberState", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(32434, "collectableFDesertA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(35329, "expOrb", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(36579, "collectableDesertA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(37885, "lifeCellBooleanUberState", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(45954, "xpOrbUberState", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(48993, "xpOrbBUberState", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(52086, "collectableCDesertA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(54275, "xpOrbB", SerializedBooleanUberState, false)
DEFINE_STATE(54494, SerializedBooleanUberState, false)  // gorlekOre
DEFINE_NAMED_STATE(56821, "collectableADesertA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(60605, "collectableGDesertA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(61548, "xpOrbAUberState", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(62117, "keystoneBUberState", SerializedBooleanUberState, false)

#undef GROUP_ID
#undef GROUP_NAME
#define GROUP_ID 8246
#define GROUP_NAME "statsUberStateGroup"
DEFINE_NAMED_STATE(3307, "timeAirborneStatSettingSerializedUberState", SerializedFloatUberState, 0.0)
DEFINE_NAMED_STATE(5144, "totalSpiritLightCollectedSerializedIntUberState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(7293, "timeGlowingStatSettingSerializedUberState", SerializedFloatUberState, 0.0)
DEFINE_NAMED_STATE(7909, "fastTravelCountIntUberState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(7927, "enemiesPiercedAtOnceStatSettingSerializedUberState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(8682, "distanceSwamStatSettingSerializedFloatUberState", SerializedFloatUberState, 0.0)
DEFINE_NAMED_STATE(12323, "deathFromEnemiesStatSettingSerializedUberState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(15506, "npcsInHubStatSettingSerializedUberState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(16123, "distanceGlidedStatSettingSerializedFloatUberState", SerializedFloatUberState, 0.0)
DEFINE_NAMED_STATE(17772, "bashesStatSettingSerializedUberState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(18554, "shardSlotUpgradesCollectedStatSettingSerializedUberState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(23469, "shrinesDiscoveredGreaterThanOneCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(23590, "enemyVsEnemyKillsGreaterThanOneCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(26408, "racesCompletedGreaterThanOneCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(26498, "mostDefeatedEnemyEnumStatSettingSerializedUberState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(28073, "totalDamageTakenStatSettingSerializedUberState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(28832, "fastTravelsGreaterThanOneCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(30164, "wallJumpsStatSettingSerializedUberState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(30251, "spiritLightCollectedStatSettingSerializedUberState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(31025, "deathsEnvironmentalGreaterThanOneCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(31056, "sideQuestsCompletedStatSettingSerializedUberState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(31216, "enemyVsEnemyKillsStatSettingSerializedUberState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(32860, "enemiesDefeatedStatSettingSerializedUberState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(35034, "deathFromEnemiesGreaterThanOneCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(36466, "deathsStatSettingSerializedUberState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(37583, "totalSpiritLightSpentSerializedIntUberState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(39039, "shardSlotUpgradesCollectedGreaterThanOneCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(39167, "drowningGreaterThanOneCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(40254, "highestAmountOfDamageSerializedIntUberState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(40261, "distanceBurrowedStatSettingSerializedFloatUberState", SerializedFloatUberState, 0.0)
DEFINE_NAMED_STATE(42772, "totalHealthRegeneratedStatSettingSerializedUberState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(43418, "timeTotalPlaytimeStatSettingSerializedUberState", SerializedFloatUberState, 0.0)
DEFINE_NAMED_STATE(44318, "gardenerSeedsCollectedStatSettingSerializedUberState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(44439, "distanceFallingStatSettingSerializedFloatUberState", SerializedFloatUberState, 0.0)
DEFINE_NAMED_STATE(46034, "racePedestalsActivateGreaterThanOneCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(47477, "timeAliveUberState", SerializedFloatUberState, 0.0)
DEFINE_NAMED_STATE(49162, "racesCompletedStatSettingSerializedUberState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(49364, "timeLongestSingleAirborneStatSettingSerializedUberState", SerializedFloatUberState, 0.0)
DEFINE_NAMED_STATE(49721, "favoriteSkillEnumStatSettingSerializedUberState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(50096, "shrinesDiscoveredStatSettingSerializedUberState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(50669, "spiritLightSpentStatSettingSerializedUberState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(50952, "dashesStatSettingSerializedUberState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(54110, "racePedestalsActivatedStatSettingSerializedUberState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(57639, "deathsEnvironmentalStatSettingSerializedUberState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(58048, "drowningDeathsStatSettingSerializedUberState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(58908, "jumpsStatSettingSerializedUberState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(59865, "shardsCollectedStatSettingSerializedUberState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(60852, "spiritWellsDiscoveredStatSettingSerializedUberState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(60940, "energySpentSerializedFloatUberState", SerializedFloatUberState, 0.0)
DEFINE_NAMED_STATE(61434, "teleportsGreaterThanOneCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(62287, "mostDefeatedByEnemyEnumStatSettingSerializedUberState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(62310, "distanceTravelledStatSettingSerializedFloatUberState", SerializedFloatUberState, 0.0)
DEFINE_NAMED_STATE(63037, "shrinesCompletedStatSettingSerializedUberState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(64519, "leashesStatSettingSerializedUberState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(64778, "teleportCountStatSettingSerializedUberState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(65007, "shrinesCompletedGreaterThanOneCondition", ConditionUberState, false)

#undef GROUP_ID
#undef GROUP_NAME
#define GROUP_ID 9593
#define GROUP_NAME "inkwaterMarshStateGroup"
DEFINE_NAMED_STATE(3621, "mokiTorchPlayed", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(5253, "expOrbA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(5929, "xpOrbA", SerializedBooleanUberState, false)
DEFINE_STATE(7849, SerializedBooleanUberState, false)  // expOrb
DEFINE_NAMED_STATE(9229, "lanternAndCreepA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(14616, "breakableLogB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(15672, "climbHintShown", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(17659, "stompableFloor", SerializedBooleanUberState, false)
DEFINE_STATE(17818, SerializedBooleanUberState, false)  // expOrb
DEFINE_NAMED_STATE(17991, "lasersDiscovered", SerializedBooleanUberState, false)
DEFINE_STATE(20382, SerializedBooleanUberState, false)  // gorlekOreA
DEFINE_NAMED_STATE(22802, "energyVessel", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(23319, "breakableWall", SerializedBooleanUberState, false)
DEFINE_STATE(23858, SerializedBooleanUberState, false)  // gorlekOreA
DEFINE_NAMED_STATE(24376, "mapIconDoubleJumpTreeVisibleCondition", ConditionUberState, true)
DEFINE_NAMED_STATE(25130, "lizardMultiWaveArenaInt", SerializedIntUberState, 0)
DEFINE_STATE(25989, SerializedBooleanUberState, false)  // gorlekOreA
DEFINE_NAMED_STATE(26238, "lanternAndCreepB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(26457, "energyContainer", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(27562, "halfEnergyCellA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(31687, "swampArenaAInt", SerializedIntUberState, 0)
DEFINE_STATE(34704, SerializedBooleanUberState, false)  // secretWallA
DEFINE_NAMED_STATE(42047, "xpOrb", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(43576, "lizardMultiWaveArena", IntUberState, 0)
DEFINE_NAMED_STATE(45142, "swampArenaA", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(45321, "xpOrbB", SerializedBooleanUberState, false)
DEFINE_STATE(47420, SerializedBooleanUberState, false)  // secretWallA
DEFINE_STATE(53947, SerializedBooleanUberState, false)  // expOrb
DEFINE_STATE(59344, SerializedBooleanUberState, false)  // expOrb
DEFINE_NAMED_STATE(59418, "enemyRoom", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(61304, "healthContainer", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(62965, "mapIconMeditateTreeVisibleCondition", ConditionUberState, false)

#undef GROUP_ID
#undef GROUP_NAME
#define GROUP_ID 10289
#define GROUP_NAME "windtornRuinsGroup"
DEFINE_NAMED_STATE(93, "rotatingBlockSetupRotation", SerializedIntUberState, 0)
DEFINE_STATE(94, SerializedBooleanUberState, false)  // drillZoneA
DEFINE_NAMED_STATE(312, "powerLineIntUberStateA", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(1620, "goldenSeinBarrierD", SerializedBooleanUberState, false)
DEFINE_STATE(3217, SerializedIntUberState, 0)  // powerLineIntUberState
DEFINE_NAMED_STATE(3621, "ruinsVisited", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(3682, "powerLineIntUberStateC", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(3804, "openedDesertRuins", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(4154, "goldenSeinBarrierB", SerializedBooleanUberState, false)
DEFINE_STATE(4928, SavePedestalUberState, false)  // savePedestalUberState
DEFINE_NAMED_STATE(5546, "wormDistanceStateA", SerializedFloatUberState, 0.0)
DEFINE_NAMED_STATE(5814, "wormDistanceStateD", SerializedFloatUberState, 0.0)
DEFINE_NAMED_STATE(6414, "wormNodeStateB", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(7638, "baseKillzoneState", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(8436, "bombableWallDesertC", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(8533, "drillZoneD", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(10093, "drillZoneF", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(10828, "wormDistanceStateC", SerializedFloatUberState, 0.0)
DEFINE_NAMED_STATE(11244, "canOpenDesertRuins", ConditionUberState, true)
DEFINE_NAMED_STATE(12614, "wormNodeStateC", SerializedIntUberState, 0)
DEFINE_STATE(12859, SerializedBooleanUberState, false)  // drillZoneA
DEFINE_NAMED_STATE(13021, "sandwormActiveA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(13937, "DesertSavePedestal", SavePedestalUberState, false)
DEFINE_STATE(15867, SerializedBooleanUberState, false)  // drillZoneA
DEFINE_NAMED_STATE(16802, "escapeBridgeB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(16886, "wormNodeStateG", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(19890, "desertRuinsEscape", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(22102, "wispRewardPickup", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(23855, "wormNodeStateF", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(23922, "goldenSeinBarrierC", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(27089, "collapseSequenceB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(27929, "escapeRockI", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(27997, "wormNodeStateA", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(28779, "escapeRockC", SerializedBooleanUberState, false)
DEFINE_STATE(29069, SerializedBooleanUberState, false)  // drillZoneA
DEFINE_NAMED_STATE(29425, "fallingPillars", SerializedBooleanUberState, false)
DEFINE_STATE(30540, SerializedBooleanUberState, false)  // drillZoneA
DEFINE_NAMED_STATE(31524, "windsweptWastesRuinsDoorCannotOpen", SerializedBooleanUberState, false)
DEFINE_STATE(31750, SerializedBooleanUberState, false)  // drillZoneA
DEFINE_NAMED_STATE(32483, "escapeRockG", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(32833, "escapeRockE", SerializedBooleanUberState, false)
DEFINE_STATE(35130, SerializedIntUberState, 0)  // powerLineIntUberState
DEFINE_NAMED_STATE(35190, "wormDistanceToNextNodeState", SerializedFloatUberState, 0.0)
DEFINE_NAMED_STATE(36008, "wormDistanceStateH", SerializedFloatUberState, 0.0)
DEFINE_STATE(36274, SerializedBooleanUberState, false)  // drillZoneB
DEFINE_NAMED_STATE(37849, "windtornRuinsAKeystoneDoor", SerializedBooleanUberState, false)
DEFINE_STATE(38171, SerializedBooleanUberState, false)  // drillZoneC
DEFINE_STATE(38721, SerializedBooleanUberState, false)  // drillZoneA
DEFINE_NAMED_STATE(40310, "escapeRockF", SerializedBooleanUberState, false)
DEFINE_STATE(40484, SavePedestalUberState, false)  // savePedestalUberState
DEFINE_NAMED_STATE(40790, "goldenSeinBarrierA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(41277, "lever", SerializedBooleanUberState, false)
DEFINE_STATE(41902, SerializedBooleanUberState, false)  // drillZoneB
DEFINE_NAMED_STATE(43103, "rootBreakPillarFall", SerializedBooleanUberState, false)
DEFINE_STATE(44426, SerializedBooleanUberState, false)  // drillZoneB
DEFINE_NAMED_STATE(44555, "energyHalfCell", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(45179, "escapeEndRocks", SerializedBooleanUberState, false)
DEFINE_STATE(45766, SerializedBooleanUberState, false)  // drillZoneA
DEFINE_NAMED_STATE(45821, "wormNodeStateE", SerializedIntUberState, 0)
DEFINE_STATE(46316, SerializedBooleanUberState, false)  // drillZoneB
DEFINE_NAMED_STATE(47857, "wormNodeState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(48372, "healthHalfCell", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(48604, "keystoneDoor", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(50264, "wormNodeStateD", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(50961, "escapeRockJ", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(51149, "wormDistanceStateB", SerializedFloatUberState, 0.0)
DEFINE_NAMED_STATE(52211, "wormDistanceStateE", SerializedFloatUberState, 0.0)
DEFINE_NAMED_STATE(52478, "wormBreakFloor", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(54236, "desertRuinsEscapeSequenceCompleted", ConditionUberState, false)
DEFINE_STATE(55317, SerializedBooleanUberState, false)  // drillZoneA
DEFINE_NAMED_STATE(55672, "drillZoneE", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(55692, "escapeRockH", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(55787, "bombableWall", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(56515, "wormNodeStateH", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(57325, "escapeRockA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(58175, "wormDistanceStateF", SerializedFloatUberState, 0.0)
DEFINE_NAMED_STATE(58350, "powerLineIntUberStateB", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(60565, "desertRuinsWispSequencePlayed", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(61217, "areaText", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(61615, "xpOrbA", SerializedBooleanUberState, false)
DEFINE_STATE(62291, SerializedBooleanUberState, false)  // drillZoneC
DEFINE_NAMED_STATE(62926, "collapseSequenceA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(63154, "escapeRockD", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(63700, "desertSruinsChaseSandWall", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(63894, "wormDistanceStateG", SerializedFloatUberState, 0.0)
DEFINE_STATE(64240, SerializedBooleanUberState, false)  // drillZoneA
DEFINE_NAMED_STATE(65145, "escapeRockB", SerializedBooleanUberState, false)

#undef GROUP_ID
#undef GROUP_NAME
#define GROUP_ID 11666
#define GROUP_NAME "howlsDenGRoup"
DEFINE_NAMED_STATE(4220, "hasOriUsedSavePedestal", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(4932, "saveRoomDoor", SerializedBooleanUberState, false)
DEFINE_STATE(16542, SavePedestalUberState, false)  // savePedestalUberState
DEFINE_STATE(20829, SavePedestalUberState, false)  // savePedestalUberState
DEFINE_NAMED_STATE(24943, "howlsDenLargeXPOrbA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(42038, "areaText", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(61594, "savePedestal", SavePedestalUberState, false)

#undef GROUP_ID
#undef GROUP_NAME
#define GROUP_ID 13298
#define GROUP_NAME "leaderboardsUberStateGroup"
DEFINE_NAMED_STATE(3608, "baursReachLeaderboardPlaceState", SerializedIntUberState, -1)
DEFINE_NAMED_STATE(4929, "desertLeaderboardPlaceState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(6736, "hornbugBossLeaderboardPlaceState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(14784, "watermillEscapeLeaderboardPlaceState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(20341, "laserShooterMiniBossLeaderboardPlaceState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(37881, "kwolokBossLeaderboardPlaceState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(40104, "inkwaterLeaderboardPlaceState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(41733, "spiderBossLeaderboardPlaceState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(44392, "desertEscapeLeaderboardPlaceState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(53149, "kwoloksLeaderboardPlaceState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(53528, "avalancheEscapeLeaderboardPlaceState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(53967, "wellspringLeaderboardPlaceState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(54921, "baursReachLeaderboardNotificationState", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(55577, "silentWoodlandLeaderboardPlaceState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(58679, "lumaPoolsLeaderboardPlaceState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(59179, "mouldwoodLeaderboardPlaceState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(64962, "owlBossLeaderboardPlaceState", SerializedIntUberState, 0)

#undef GROUP_ID
#undef GROUP_NAME
#define GROUP_ID 13428
#define GROUP_NAME "bashIntroductionA__clone1Group"
DEFINE_NAMED_STATE(59730, "healthContainerA", SerializedBooleanUberState, false)

#undef GROUP_ID
#undef GROUP_NAME
#define GROUP_ID 14019
#define GROUP_NAME "questUberStateGroup"
DEFINE_NAMED_STATE(353, "gardenerHutDiscovered", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(1182, "braveMokiItemCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(1341, "helpingHandQuestUberState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(1581, "mineGemItemCollectedCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(2763, "collectedAllWispsCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(2782, "darkCaveQuestItemCollected", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(3030, "npcTradeSequence8StringMokiHappyCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(3852, "FirstRaceRumorMokCanGiveRumor", ConditionUberState, true)
DEFINE_NAMED_STATE(3962, "hasDesertWispCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(4002, "hasWinterForestWispCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(5085, "npcGardenerHappyCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(5234, "gardenerInHub", ConditionUberState, false)
DEFINE_NAMED_STATE(5662, "firstRaceDiscovered", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(5737, "reachWaterMillQuestUberState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(5956, "kwolokFoundLumaPoolsCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(6091, "npcOpherHappyCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(6122, "MouldwoodRumorMokiCanGiveRumor", ConditionUberState, true)
DEFINE_NAMED_STATE(6284, "dialogQuest", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(7470, "gardenerSeedTreeCollected", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(8192, "gardenerSeedBashCollected", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(8973, "winterForestWispQuestUberState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(9716, "kwolokIsDeadCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(9753, "hasSpringSeedCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(9874, "mapstoneDiscovered", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(10381, "gardenerFrozen", ConditionUberState, true)
DEFINE_NAMED_STATE(10508, "hasAncientTabletCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(11308, "baursReachJTokkInteractionQuest", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(11894, "familyReunionHouseBuiltCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(12052, "actOneCompletedCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(12109, "canGiveTheElderQuestCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(12437, "howlsDenShrineRumorMokiState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(12642, "mouldwoodDiscovered", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(13020, "wotwQuestUberState", CountUberState, 0)
DEFINE_NAMED_STATE(13091, "spiderlingCanGiveRumor", ConditionUberState, true)
DEFINE_NAMED_STATE(13512, "mouldwoodRumorMokiState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(14567, "wellspringQuestInProgressCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(14931, "lanternItemCollected", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(15983, "braveMokiQuest", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(15995, "wellspringShrineRumorMokiState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(16416, "hasFirstWispCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(16509, "wellspringShrineRumorState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(17658, "kwoloksWisdomItemCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(18061, "mouldwoodShrineRumorState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(18110, "marshKeystoneCollectedCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(18220, "npcTradeSequence10GotMapstoneHappyCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(19024, "lagoonRumorState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(19060, "desertRuinsRumorState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(19157, "brothersQuest", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(19386, "motayCanGiveRumor", ConditionUberState, false)
DEFINE_NAMED_STATE(20241, "npcTradeSequence7GotSilkCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(20290, "howlsOriginWellOpened", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(20601, "gardenerSeedFlowersCollected", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(20667, "lostCompassQuest", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(21068, "hasGrappleSeedCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(23161, "giveWellspringQuestCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(23360, "howlsDenShrineRumorMokiCanGiveRumor", ConditionUberState, true)
DEFINE_NAMED_STATE(23459, "gardenerIntroQuest", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(23762, "hasPetrifiedDollCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(23787, "lastTreeQuest", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(23863, "inkwaterShrineRumorState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(24142, "gardenerSeedGrappleCollected", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(24152, "optionalVSQuestAUberState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(24265, "hasLagoonWispCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(24683, "luposMapQuest", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(25679, "npcTradeSequence3GotHerbsCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(26148, "wispCountUberState", CountUberState, 0)
DEFINE_NAMED_STATE(26318, "tradeSequenceQuest", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(26394, "regrowGladesQuest", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(27011, "silentWoodsShrineRumorState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(27270, "wellspringShrineDiscovered", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(27382, "hasGrassSeedCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(27539, "braveMokiItemCollected", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(27727, "npcTwillenHappyCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(27804, "familyReunionQuest", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(27822, "howlsDenShrineRumorState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(27891, "hasMouldwoodWispCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(28050, "hasFlowerSeedCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(28576, "luposMapQuestProgressCount", CountUberState, 0)
DEFINE_NAMED_STATE(28662, "gardenerSeedGrassCollected", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(29163, "desertDiscovered", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(29202, "lagoonDiscovered", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(30596, "gardenerHutRumorState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(30653, "npcDarkCaveMokiHappyCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(30671, "howlsOriginDiscovered", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(31055, "hasMokiKeyCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(31413, "desertRuinsDiscovered", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(31606, "darkCaveQuestEntranceOpenCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(31978, "hasPetrifiedBranchCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(32112, "LagoonRumorMokiCanGiveRumorCondition", ConditionUberState, true)
DEFINE_NAMED_STATE(32376, "gardenerSeedSpringCollected", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(33031, "GromCanGiveRumor", ConditionUberState, false)
DEFINE_NAMED_STATE(33762, "freeGromQuestUberState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(33776, "darkCaveQuest", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(34120, "npcOrphanageMokiHappyCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(34504, "findKuQuest", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(34744, "watermillOttersActive", ConditionUberState, false)
DEFINE_NAMED_STATE(35087, "lagoonWispQuestUberState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(35399, "desertWispQuestUberState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(35534, "mapSecretsRevealed", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(36248, "howlsDenShrineDiscovered", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(37086, "npcKwoloksWisdomMokiHappyCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(37857, "npcTradeSequence4GotFoodCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(38680, "npcTradeSequence2GotBackpackCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(39957, "mapstoneRumorState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(40630, "inkwaterShrineDiscovered", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(40952, "howlsOriginRumorState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(42501, "firstRaceRumorState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(44059, "findHelpQuestUberState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(44184, "baurRumorState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(44500, "lookForKuQuestUberState", SerializedIntUberState, 4)
DEFINE_NAMED_STATE(44578, "rebuildGladesQuest", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(45010, "returnsAfterWaterCleansedCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(45830, "npcLupoHappyCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(45931, "mouldwoodDepthsWispQuestUberState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(46529, "baurDiscovered", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(47774, "lagoonRumorMokiState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(48525, "hasIronNeedleCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(48794, "findToadQuestUberState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(49049, "npcTradeSequence9GotCanteenHappyCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(49299, "notCollectedAllWispsCondition", ConditionUberState, true)
DEFINE_NAMED_STATE(49333, "npcTradeSequence8GotSpyglassCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(50230, "baurRumorMokiState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(50571, "swampSpringIntroductionBOpherInteractionQuest", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(50597, "kwoloksWisdomQuest", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(50847, "discoveredWillowsEnd", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(51000, "npcMokkTheBraveHappyCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(51223, "wellspringShrineRumorMokiCanGiveRumor", ConditionUberState, false)
DEFINE_NAMED_STATE(51598, "npcTokkHappyCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(51616, "hasMysteriousGemCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(52274, "silentWoodsShrineDiscovered", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(52747, "howlsOriginTreasureCollected", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(53066, "mouldwoodRumorState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(53075, "hasNotMouldwoodWispCondition", ConditionUberState, true)
DEFINE_NAMED_STATE(53103, "kwoloksWisdomItemCollected", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(54654, "npcTradeSequence5GotHatCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(54675, "lastGlobalEvent", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(54970, "mouldwoodShrineDiscovered", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(56007, "npcTradeSequence1GotDrawingCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(57066, "killTentacleQuestUberState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(57399, "familyReunionItemCollected", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(57552, "desertRumorState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(58342, "mineGemItemCollected", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(59705, "searchForGrolQuest", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(59708, "treeKeeperQuest", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(59725, "hasNotLagoonWispCondition", ConditionUberState, true)
DEFINE_NAMED_STATE(59849, "npcTradeSequence6GotLanternCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(60165, "BaurRumorMokiCanGiveRumor", ConditionUberState, true)
DEFINE_NAMED_STATE(60646, "inDangerBool", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(60924, "hasTreeSeedCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(61011, "desertCogQuest", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(61129, "npcTreekeeperHappyCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(61241, "hasBashPlantsSeedCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(61500, "npcTradeSequenceFishermanStillThereCondition", ConditionUberState, true)
DEFINE_NAMED_STATE(61975, "wellspringQuestCompletedCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(62180, "hasPetrifiedForestWispCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(62230, "getInitialWeaponQuestUberState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(62288, "firstRaceRumorMokiState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(63396, "desertCogItemCollected", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(63965, "discoveredWeepingRidge", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(64760, "hasAcornCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(65451, "kuDiedCondition", ConditionUberState, false)

#undef GROUP_ID
#undef GROUP_NAME
#define GROUP_ID 16155
#define GROUP_NAME "willowsEndGroup"
DEFINE_STATE(2065, SerializedBooleanUberState, false)  // expOrb
DEFINE_NAMED_STATE(2235, "fallingPortalB", SerializedBooleanUberState, false)
DEFINE_STATE(3096, SerializedBooleanUberState, false)  // breakableWallA
DEFINE_NAMED_STATE(3588, "vineEClear", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(3670, "arenaPlatform3Destroyed", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(5826, "arenaPlatform2Destroyed", SerializedBooleanUberState, false)
DEFINE_STATE(9230, SerializedBooleanUberState, false)  // gorlekOreA
DEFINE_NAMED_STATE(9580, "laserShooterBossNotDefeated", ConditionUberState, true)
DEFINE_NAMED_STATE(11019, "lessThanTwoVinesCleared", ConditionUberState, true)
DEFINE_NAMED_STATE(12971, "laserShooterBossState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(18906, "fallingPortal", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(20672, "creepA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(21083, "chaseSequenceG", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(21619, "twoToThreeVinesCleared", ConditionUberState, false)
DEFINE_STATE(21899, SerializedBooleanUberState, false)  // breakableWallC
DEFINE_NAMED_STATE(22708, "countClearVines", CountUberState, 0)
DEFINE_NAMED_STATE(24290, "vineCClear", SerializedBooleanUberState, false)
DEFINE_STATE(25259, SerializedBooleanUberState, false)  // xpOrbA
DEFINE_NAMED_STATE(26338, "sixToSevenVinesCleared", ConditionUberState, false)
DEFINE_NAMED_STATE(27024, "chaseSequenceA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(28478, "vineDClear", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(32922, "introPlayed", SerializedBooleanUberState, false)
DEFINE_STATE(33738, SerializedBooleanUberState, false)  // breakableWallC
DEFINE_NAMED_STATE(36353, "secretWall", SerializedBooleanUberState, false)
DEFINE_STATE(36873, SerializedBooleanUberState, false)  // breakableWallA
DEFINE_STATE(37558, SerializedBooleanUberState, false)  // breakableWallB
DEFINE_NAMED_STATE(37648, "chaseSequenceC", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(38867, "chaseSequenceD", SerializedBooleanUberState, false)
DEFINE_STATE(38979, SerializedBooleanUberState, false)  // gorlekOreA
DEFINE_STATE(41465, SavePedestalUberState, false)  // savePedestalUberState
DEFINE_NAMED_STATE(41488, "vineGClear", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(42106, "secretWallA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(42976, "vineAClear", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(44311, "chaseSequenceB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(45630, "arenaPlatform1Destroyed", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(46270, "healthCellA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(47278, "petrifiedOwlBossState", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(47690, "expOrbB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(49381, "expOrbA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(49408, "chaseSequenceE", SerializedBooleanUberState, false)
DEFINE_STATE(49457, SerializedBooleanUberState, false)  // expOrb
DEFINE_NAMED_STATE(49744, "chaseSequenceF", SerializedBooleanUberState, false)
DEFINE_STATE(50867, SavePedestalUberState, false)  // savePedestalUberState
DEFINE_STATE(52848, SerializedBooleanUberState, false)  // breakableWallB
DEFINE_NAMED_STATE(53319, "fourToFiveVinesCleared", ConditionUberState, false)
DEFINE_NAMED_STATE(54148, "groundDestroyed", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(54940, "vineBClear", SerializedBooleanUberState, false)
DEFINE_STATE(55446, SerializedBooleanUberState, false)  // xpOrbA
DEFINE_NAMED_STATE(55721, "fallingPortalA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(57370, "allVinesCleared", ConditionUberState, false)
DEFINE_NAMED_STATE(60752, "vineHClear", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(63705, "arenaPlatform4Destroyed", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(65277, "vineFClear", SerializedBooleanUberState, false)

#undef GROUP_ID
#undef GROUP_NAME
#define GROUP_ID 18793
#define GROUP_NAME "mouldwoodDepthsGroup"
DEFINE_STATE(836, SerializedBooleanUberState, false)  // orePickupA
DEFINE_NAMED_STATE(1914, "keystone", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(2105, "spiderBossDefeatedCondition", ConditionUberState, false)
DEFINE_STATE(2881, SerializedBooleanUberState, false)  // expOrbB
DEFINE_STATE(3171, SerializedBooleanUberState, false)  // doorWithFourSlots
DEFINE_NAMED_STATE(4645, "blockerWallBroken", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(4664, "creepDestroyedA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(5315, "secretWall", SerializedBooleanUberState, false)
DEFINE_STATE(5797, SerializedBooleanUberState, false)  // expOrbB
DEFINE_STATE(6573, SerializedBooleanUberState, false)  // expOrbB
DEFINE_NAMED_STATE(8973, "canOpenMouldwoodGate", ConditionUberState, false)
DEFINE_STATE(9251, SerializedBooleanUberState, false)  // expOrbA
DEFINE_STATE(10372, SerializedBooleanUberState, false)  // doorWithFourSlots
DEFINE_NAMED_STATE(10758, "mouldwoodDepthsGDoorWithTwoSlotsOpened", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(11676, "creepB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(12512, "shrineEnemies", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(12854, "mapIconFlashTreeVisibleCondition", ConditionUberState, true)
DEFINE_NAMED_STATE(12933, "shouldStartSpiderBossFight", ConditionUberState, false)
DEFINE_NAMED_STATE(13281, "kwolokCavernsBreakableFloor", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(13349, "shortcutWall", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(13352, "darknessLiftedUberState", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(13367, "lanternAndCreepB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(14503, "leverAndDoorA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(15396, "xpOrbC", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(15422, "arenaBottomBrokenFloor", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(15855, "mouldwoodDepthsHBreakableWallB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(18064, "chamberWebFBroken", SerializedBooleanUberState, false)
DEFINE_STATE(18395, SerializedBooleanUberState, false)  // XPOrbA
DEFINE_NAMED_STATE(18563, "chamberWebEBroken", SerializedBooleanUberState, false)
DEFINE_STATE(19004, SerializedBooleanUberState, false)  // mediumExpA
DEFINE_NAMED_STATE(20493, "mouldwoodDepthsJKeystoneBCollected", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(20959, "mouldwoodDepthsJKeystoneCCollected", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(21022, "breakableWallA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(21994, "puzzleSolvedSequenceCompleted", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(22368, "lanternAndCreepA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(23799, "expOrbC", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(23953, "areaText", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(23986, "mouldwoodDepthsHKeystoneBCollected", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(25789, "mouldwoodGateOpen", SerializedBooleanUberState, false)
DEFINE_STATE(26618, SerializedBooleanUberState, false)  // energyContainerA
DEFINE_NAMED_STATE(26713, "spiderBossState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(27207, "stompableFloor", SerializedBooleanUberState, false)
DEFINE_STATE(28175, SerializedBooleanUberState, false)  // energyContainerA
DEFINE_NAMED_STATE(28205, "spiderIntereactedAfterFight", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(28516, "allCreepDestroyed", ConditionUberState, false)
DEFINE_NAMED_STATE(28677, "breakableWebB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(28692, "brokenTrunkTop", SerializedBooleanUberState, false)
DEFINE_STATE(29066, SerializedBooleanUberState, false)  // creepA
DEFINE_STATE(29533, SerializedBooleanUberState, false)  // mediumExpA
DEFINE_STATE(29979, SerializedBooleanUberState, false)  // expOrbA
DEFINE_NAMED_STATE(30627, "mouldwoodDepthsHPushBlockPushed", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(30708, "mouldwoodDepthsJKeystoneDCollected", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(31937, "shardSlotUpgradePlaceholder", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(32305, "chamberWebBBroken", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(32441, "mouldwoodDepthsJKeystoneACollected", SerializedBooleanUberState, false)
DEFINE_STATE(33471, SerializedBooleanUberState, false)  // doorWithFourSlots
DEFINE_STATE(35351, SerializedBooleanUberState, false)  // orePickupA
DEFINE_STATE(38871, SavePedestalUberState, false)  // savePedestalUberState
DEFINE_NAMED_STATE(38941, "expOrb", SerializedBooleanUberState, false)
DEFINE_STATE(39232, SerializedBooleanUberState, false)  // creepA
DEFINE_NAMED_STATE(39667, "lanternAndCreepBInt", SerializedIntUberState, 0)
DEFINE_STATE(39689, SavePedestalUberState, false)  // savePedestalUberState
DEFINE_NAMED_STATE(40612, "lanternAndCreepCTest", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(41544, "mouldwoodDepthsHDoorWithFourSlotsOpened", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(42235, "healthCellB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(42980, "mediumExpB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(43973, "arena2ReachedCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(44522, "webFallState", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(44773, "leafPileA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(45899, "hintZoneFlash", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(45963, "bottomRightSmallWall", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(49362, "verticalFallingTrunk", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(49526, "XPOrbB", SerializedBooleanUberState, false)
DEFINE_STATE(49759, SerializedBooleanUberState, false)  // XPOrbA
DEFINE_NAMED_STATE(50745, "hintZoneFlashCharge", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(53347, "arenaTrunkBroken", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(53953, "mouldwoodDepthsHKeystoneACollected", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(56320, "breakableWebA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(56666, "arenaBreakableA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(56800, "bottomLeftSmallWall", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(58148, "keystoneA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(58342, "mediumExpC", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(62694, "healthCellA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(63291, "bossReward", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(64305, "arenaWallMid", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(64475, "arena1WallBrokenCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(64772, "mouldwoodDepthsHBreakableWallA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(65202, "secretWallA", SerializedBooleanUberState, false)

#undef GROUP_ID
#undef GROUP_NAME
#define GROUP_ID 19973
#define GROUP_NAME "eventsUberStateGroup"
DEFINE_NAMED_STATE(18551, "gumoFreeUberState", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(22047, "spiritTreeReachedUberState", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(23591, "mistLiftedUberState", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(30524, "ginsoTreeKeyUberState", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(31305, "kwolokDeadUberState", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(38631, "mountHoruKeyUberState", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(45830, "kwolokLeftThroneUberState", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(49418, "gravityActivatedUberState", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(54999, "ginsoTreeEnteredUberState", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(59537, "windRestoredUberState", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(61347, "forlornRuinsKeyUberState", SerializedBooleanUberState, false)

#undef GROUP_ID
#undef GROUP_NAME
#define GROUP_ID 20120
#define GROUP_NAME "windsweptWastesGroupDescriptor"
DEFINE_NAMED_STATE(224, "expOrb", SerializedBooleanUberState, false)
DEFINE_STATE(1348, SerializedBooleanUberState, false)  // bombableWallA
DEFINE_NAMED_STATE(2013, "xpOrbG", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(2552, "areaText", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(3550, "xpOrbC", SerializedBooleanUberState, false)
DEFINE_STATE(8910, SerializedBooleanUberState, false)  // xpOrbA
DEFINE_NAMED_STATE(9095, "breakableWall", SerializedBooleanUberState, false)
DEFINE_STATE(10397, SerializedBooleanUberState, false)  // xpOrbB
DEFINE_NAMED_STATE(10801, "xpOrbD", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(11785, "energyHalfCell", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(12902, "leverStateA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(12941, "healthContainer", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(16172, "projectileBreakableWall", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(16309, "digHint", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(17798, "expOrbE", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(18965, "lifeHalfCell", SerializedBooleanUberState, false)
DEFINE_STATE(19113, SerializedBooleanUberState, false)  // xpOrbB
DEFINE_NAMED_STATE(22354, "energyOrbA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(24078, "digDashHint", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(24774, "drillableWallA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(28786, "e3DesertG_clone0_KeystoneDoor", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(30358, "xpOrbE", SerializedBooleanUberState, false)
DEFINE_STATE(30740, SerializedBooleanUberState, false)  // xpOrbA
DEFINE_NAMED_STATE(31180, "drillableBlockerA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(33275, "expOrbB", SerializedBooleanUberState, false)
DEFINE_STATE(33292, SerializedBooleanUberState, false)  // shardA
DEFINE_NAMED_STATE(33294, "bombableWallC", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(33775, "bombableWallB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(36758, "drillWallA", SerializedBooleanUberState, false)
DEFINE_STATE(36805, SerializedBooleanUberState, false)  // xpOrbA
DEFINE_NAMED_STATE(40245, "gorlekOreB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(40816, "hintZoneA", SerializedBooleanUberState, false)
DEFINE_STATE(41398, SavePedestalUberState, false)  // savePedestalUberState
DEFINE_STATE(42393, SerializedBooleanUberState, false)  // xpOrbA
DEFINE_NAMED_STATE(43099, "shootablePod", SerializedBooleanUberState, false)
DEFINE_STATE(43231, SerializedBooleanUberState, false)  // bombableWall
DEFINE_STATE(46919, SerializedBooleanUberState, false)  // gorlekOre
DEFINE_NAMED_STATE(48009, "verticalPlatformLeverA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(48829, "expOrbD", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(49950, "hintZoneB", SerializedBooleanUberState, false)
DEFINE_STATE(49985, SerializedBooleanUberState, false)  // shardA
DEFINE_STATE(49994, SavePedestalUberState, false)  // savePedestalUberState
DEFINE_NAMED_STATE(50026, "energyContainer", SerializedBooleanUberState, false)
DEFINE_STATE(51985, SerializedBooleanUberState, false)  // bombableWallA
DEFINE_NAMED_STATE(52812, "xpOrb", SerializedBooleanUberState, false)
DEFINE_STATE(54936, SerializedBooleanUberState, false)  // bombableWall
DEFINE_NAMED_STATE(55057, "creepA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(55196, "wispSequencePlayedOut", SerializedBooleanUberState, false)
DEFINE_STATE(55303, SerializedBooleanUberState, false)  // gorlekOre
DEFINE_NAMED_STATE(55388, "bombableWallE", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(56688, "mapIconDigTreeVisibleCondition", ConditionUberState, true)
DEFINE_STATE(57133, SerializedBooleanUberState, false)  // xpOrbA
DEFINE_STATE(57781, SerializedBooleanUberState, false)  // xpOrbB
DEFINE_NAMED_STATE(59046, "halfLifeCell", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(59275, "breakableWallA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(60953, "doorClosingPlayed", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(60960, "bombableWallD", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(61572, "bombableWallF", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(62264, "lifeCellA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(63310, "xpOrbF", SerializedBooleanUberState, false)

#undef GROUP_ID
#undef GROUP_NAME
#define GROUP_ID 20190
#define GROUP_NAME "uiGroup"
DEFINE_NAMED_STATE(31212, "displayedSpiritWellFirstUseHint", SerializedBooleanUberState, false)

#undef GROUP_ID
#undef GROUP_NAME
#define GROUP_ID 21194
#define GROUP_NAME "minesUberStateGroup"
DEFINE_STATE(685, SavePedestalUberState, false)  // savePedestalUberState
DEFINE_NAMED_STATE(6799, "stompableFloorB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(7318, "collectableC", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(11371, "spiritShardA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(16526, "collectableA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(17773, "gateState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(18508, "grolDefeated", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(26302, "collectableB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(27102, "xpOrbA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(29515, "memoriesPlayed", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(29822, "crusherActivated", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(29973, "canPlayMemories", ConditionUberState, false)
DEFINE_NAMED_STATE(34225, "minesElevatorUberState", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(35345, "elevatorDoorsBottom", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(36700, "stompableFloorA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(38411, "grolCuredIntroDialoguePlayed", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(43575, "elevatorDoorsTop", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(48792, "breakableWall", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(52416, "enemyDoor", SerializedBooleanUberState, false)
DEFINE_STATE(63334, SavePedestalUberState, false)  // savePedestalUberState
DEFINE_NAMED_STATE(63648, "leverA", SerializedBooleanUberState, false)

#undef GROUP_ID
#undef GROUP_NAME
#define GROUP_ID 21786
#define GROUP_NAME "swampStateGroup"
DEFINE_NAMED_STATE(808, "boneBridgeBroken", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(876, "creepDoorD", SerializedBooleanUberState, false)
DEFINE_STATE(2046, SerializedBooleanUberState, false)  // gorlekOreA
DEFINE_NAMED_STATE(2852, "laserPuzzleSolved", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(2869, "enemyRoom", SerializedBooleanUberState, false)
DEFINE_STATE(3714, SavePedestalUberState, false)  // savePedestal
DEFINE_STATE(6987, SerializedBooleanUberState, false)  // xpOrbA
DEFINE_STATE(6994, SerializedBooleanUberState, false)  // stompableFloor
DEFINE_STATE(7152, SerializedBooleanUberState, false)  // halfEnergyCellA
DEFINE_STATE(7709, SerializedBooleanUberState, false)  // mediumExpA
DEFINE_NAMED_STATE(7871, "mediumExpC", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(7975, "enemyArenaStateNonSerialized", IntUberState, 0)
DEFINE_NAMED_STATE(9270, "shardSlotA", SerializedBooleanUberState, false)
DEFINE_STATE(9402, SerializedBooleanUberState, false)  // creepDoorB
DEFINE_NAMED_STATE(10185, "savePedestalSwampIntroTop", SavePedestalUberState, false)
DEFINE_NAMED_STATE(10295, "energyHalfCellA", SerializedBooleanUberState, false)
DEFINE_STATE(10413, SerializedBooleanUberState, false)  // largeExpA
DEFINE_NAMED_STATE(10467, "attackableSwitchA", SerializedBooleanUberState, false)
DEFINE_STATE(11343, SerializedBooleanUberState, false)  // breakableWallA
DEFINE_NAMED_STATE(12077, "spiritShardPickupA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(12368, "playerHoldingTorchUberStateCondition", ConditionUberState, false)
DEFINE_STATE(12914, SavePedestalUberState, false)  // savePedestal
DEFINE_NAMED_STATE(16206, "xpOrbC", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(17920, "energyHalfCell", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(17957, "areaText", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(18109, "shardSlotUpgradePlaceholder", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(19679, "mediumExpB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(20144, "creepTreeC", SerializedBooleanUberState, false)
DEFINE_STATE(20160, SerializedBooleanUberState, false)  // xpOrbB
DEFINE_NAMED_STATE(20190, "notLeadToSpiritBlade", ConditionUberState, true)
DEFINE_NAMED_STATE(20194, "lifeCellA", SerializedBooleanUberState, false)
DEFINE_STATE(20615, SerializedBooleanUberState, false)  // hintZone
DEFINE_STATE(21727, SerializedBooleanUberState, false)  // largeExpA
DEFINE_NAMED_STATE(22068, "keyStone", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(22091, "pushBlockState", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(22367, "playedOutKeystoneSequence", SerializedBooleanUberState, false)
DEFINE_STATE(22570, SerializedBooleanUberState, false)  // breakableWallA
DEFINE_STATE(23154, SerializedBooleanUberState, false)  // mediumExpA
DEFINE_NAMED_STATE(23166, "pickedUpKeystoneCondition", ConditionUberState, false)
DEFINE_STATE(23177, SerializedBooleanUberState, false)  // creepDoor
DEFINE_NAMED_STATE(25095, "nightCrawlerEscaped", SerializedBooleanUberState, false)
DEFINE_STATE(25147, SerializedBooleanUberState, false)  // creepDoorA
DEFINE_NAMED_STATE(25291, "creepDoorE", SerializedBooleanUberState, false)
DEFINE_STATE(25761, SerializedBooleanUberState, false)  // healthContainerA
DEFINE_NAMED_STATE(26462, "interactedWithOpher", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(27433, "keyStoneA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(28474, "hasBothEyestonesCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(28908, "halfHealthCellA", SerializedBooleanUberState, false)
DEFINE_STATE(29636, SerializedBooleanUberState, false)  // creepDoorB
DEFINE_STATE(29892, SerializedBooleanUberState, false)  // gorlekOreA
DEFINE_STATE(30305, SerializedBooleanUberState, false)  // spiritShardA
DEFINE_NAMED_STATE(30656, "nightCrawlerChaseStarted", SerializedBooleanUberState, false)
DEFINE_STATE(30928, SerializedBooleanUberState, false)  // breakableWallA
DEFINE_STATE(31430, SerializedBooleanUberState, false)  // hintZone
DEFINE_NAMED_STATE(32430, "enemyDoorA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(32463, "creepTreeD", SerializedBooleanUberState, false)
DEFINE_STATE(33430, SerializedBooleanUberState, false)  // creepDoor
DEFINE_NAMED_STATE(34008, "breakableWallB", SerializedBooleanUberState, false)
DEFINE_STATE(35166, SerializedBooleanUberState, false)  // creepDoorA
DEFINE_NAMED_STATE(35260, "creepDoorC", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(35350, "attackableSwitchC", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(35598, "enemyArenaComplete", SerializedBooleanUberState, false)
DEFINE_STATE(35925, SerializedBooleanUberState, false)  // breakableWallA
DEFINE_NAMED_STATE(37225, "keyStoneB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(37833, "creepTreeE", SerializedBooleanUberState, false)
DEFINE_STATE(38342, SerializedBooleanUberState, false)  // hintZone
DEFINE_NAMED_STATE(38475, "bladeRitualFinished", SerializedBooleanUberState, false)
DEFINE_STATE(38720, SavePedestalUberState, false)  // savePedestal
DEFINE_NAMED_STATE(38941, "savePedestalUberState", SavePedestalUberState, false)
DEFINE_NAMED_STATE(39804, "springCreep", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(40322, "nightCrawlerDefeated", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(40424, "breakableWall", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(41817, "doorBState", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(42287, "nightcrawlerNotDefeatedCondition", ConditionUberState, true)
DEFINE_NAMED_STATE(42309, "swampTorchIntroductionADoorWithTwoSlotsBooleanDescriptor", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(43216, "watermillDiscovered", SerializedBooleanUberState, false)
DEFINE_STATE(43668, SerializedBooleanUberState, false)  // xpOrbB
DEFINE_NAMED_STATE(44157, "energyContainerA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(44253, "secretWall", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(44431, "creepTreeA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(45648, "attackableSwitchB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(46536, "nightcrawlerTeaseTimelinePlayed", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(47445, "swampNightcrawlerCavernADoorWithTwoSlotsBooleanDescriptor", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(47458, "torchHolded", SerializedBooleanUberState, false)
DEFINE_STATE(47644, SerializedBooleanUberState, false)  // creepDoorB
DEFINE_NAMED_STATE(48748, "finishedIntroTop", SerializedBooleanUberState, false)
DEFINE_STATE(49485, SerializedBooleanUberState, false)  // smallExpA
DEFINE_STATE(50255, SerializedBooleanUberState, false)  // mediumExpA
DEFINE_NAMED_STATE(50281, "swampWalljumpChallengeBKeystoneACollected", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(50432, "leverA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(50453, "leverAndDoor", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(50691, "doorAState", SerializedBooleanUberState, false)
DEFINE_STATE(50820, SavePedestalUberState, false)  // savePedestal
DEFINE_NAMED_STATE(50994, "nightcrawlerBridgeBrokenA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(50997, "mapIconBowTreeVisibleCondition", ConditionUberState, true)
DEFINE_NAMED_STATE(51018, "powlTeaseTriggered", SerializedBooleanUberState, false)
DEFINE_STATE(52026, SerializedBooleanUberState, false)  // smallExpA
DEFINE_NAMED_STATE(52815, "leverGateinkwaterMarsh", SerializedBooleanUberState, false)
DEFINE_STATE(53932, SerializedBooleanUberState, false)  // creepDoorA
DEFINE_NAMED_STATE(55881, "elevatorDown", SerializedBooleanUberState, false)
DEFINE_STATE(56901, SavePedestalUberState, false)  // savePedestal
DEFINE_NAMED_STATE(58612, "gateUberState", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(59513, "expOrb", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(59922, "breakableBridgeBroken", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(59990, "doorWithTwoSlots", SerializedBooleanUberState, false)
DEFINE_STATE(60210, SerializedBooleanUberState, false)  // healthContainerA
DEFINE_NAMED_STATE(60616, "doorFourSlots", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(61644, "ottersLeadToSpiritBlade", SerializedBooleanUberState, false)
DEFINE_STATE(61706, SerializedBooleanUberState, false)  // halfEnergyCellA
DEFINE_STATE(61900, SerializedBooleanUberState, false)  // stompableFloor
DEFINE_STATE(63072, SerializedBooleanUberState, false)  // xpOrbA
DEFINE_STATE(63545, SerializedBooleanUberState, false)  // spiritShardA
DEFINE_NAMED_STATE(64677, "swampWalljumpChallengeBKeystoneBCollected", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(65235, "creepTreeB", SerializedBooleanUberState, false)

#undef GROUP_ID
#undef GROUP_NAME
#define GROUP_ID 23987
#define GROUP_NAME "pickupsGroup"
DEFINE_NAMED_STATE(897, "hollowEnergyShardPickup", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(986, "spiritPowerShardPickup", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(9864, "recklessShardPickup", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(12104, "ultraLeashShardPickup", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(12746, "energyCell", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(14014, "focusShardPickup", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(14832, "secretShardPickup", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(19630, "untouchableShardPickup", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(20915, "spiritMagnetShardPickup", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(23015, "chainLightningPickup", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(25183, "recycleShardPickup", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(25996, "ultraBashShardPickup", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(27134, "glueShardPickup", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(31426, "counterstrikeShardPickup", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(36359, "fractureShardPickup", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(46461, "energyEfficiencyShardPickup", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(48605, "aggressorShardPickup", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(50364, "lastResortShardPickup", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(50415, "bloodPactShardPickup", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(53934, "vitalityLuckShardPickup", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(59173, "barrierShardPickup", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(61017, "frenzyShardPickup", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(62973, "splinterShardPickup", SerializedBooleanUberState, false)

#undef GROUP_ID
#undef GROUP_NAME
#define GROUP_ID 24922
#define GROUP_NAME "howlsOriginGroup"
DEFINE_NAMED_STATE(1919, "bellAState", BooleanUberState, false)
DEFINE_NAMED_STATE(2524, "secretWallA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(7459, "bellCState", BooleanUberState, false)
DEFINE_NAMED_STATE(8568, "expOrbA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(13349, "bellPuzzleSolved", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(13921, "xpOrbA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(13993, "shardSlotUpgradePlaceholder", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(16603, "portalsLifted", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(24796, "bellBState", BooleanUberState, false)
DEFINE_NAMED_STATE(32076, "smallExpA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(33535, "keystoneB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(34047, "puzzleState", ByteUberState, 0)
DEFINE_STATE(34250, SerializedBooleanUberState, false)  // keystoneA
DEFINE_NAMED_STATE(42531, "howlOriginEntranceSavePedestal", SavePedestalUberState, false)
DEFINE_NAMED_STATE(45011, "shrineArena", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(45740, "interactedWithTokk", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(46311, "spiritShard", SerializedBooleanUberState, false)
DEFINE_STATE(47244, SerializedBooleanUberState, false)  // keystoneA
DEFINE_NAMED_STATE(50740, "breakableWallA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(59146, "bellPuzzleBSolved", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(60182, "mapIconPowerTreeVisibleCondition", ConditionUberState, true)
DEFINE_STATE(60358, SerializedBooleanUberState, false)  // keystoneA
DEFINE_NAMED_STATE(62138, "largeExpA", SerializedBooleanUberState, false)

#undef GROUP_ID
#undef GROUP_NAME
#define GROUP_ID 26019
#define GROUP_NAME "convertedSetupsGymGroup"
DEFINE_NAMED_STATE(971, "blowableFlameToggle", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(1274, "secretWallA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(4052, "horizontalDoorState", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(4231, "creepDoorD", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(5259, "secretWall", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(6406, "kwolokCavernsLever", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(7636, "creepD", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(10086, "mediumExpOrb", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(11133, "snowPileB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(11592, "elevatorLever", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(12371, "stompableFloor", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(13498, "landOnAndSpawnOrbs", SerializedFloatUberState, 0.0)
DEFINE_NAMED_STATE(13586, "creepDoorA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(14277, "desertBreakableWall", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(15381, "creepC", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(18425, "stompableFloorB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(21522, "cordycepsBreakableWall", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(23282, "watermillEnemyDoor", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(23382, "leverAndDoor", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(25103, "weepingRidgeBreakableWall", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(26714, "petrifiedForestBreakableWall", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(27176, "leafPile", SerializedBooleanUberState, false)
DEFINE_STATE(28367, SerializedBooleanUberState, false)  // enemyDoor
DEFINE_NAMED_STATE(28678, "kwolokCavernsBreakableWall", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(29970, "enemyDoorA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(30549, "keyStoneYesCheckpoint", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(32221, "watermillBreakableWall", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(33339, "watermillBreakableWallUnderwater", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(33392, "lagoonEnemyDoor", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(33510, "desertRuinsBreakableWall", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(34752, "energyContainer", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(34818, "creepDoorC", SerializedBooleanUberState, false)
DEFINE_STATE(35001, SerializedBooleanUberState, false)  // snowPileA
DEFINE_NAMED_STATE(37244, "classicShootableCreepDoor", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(38710, "snowPile", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(38743, "kwolokCavernsBreakableWallLock", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(38761, "keyStoneNoCheckpoint", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(40296, "kwolokCavernsBreakableWall2", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(40553, "winterForestBreakableWall", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(44556, "creepDoorB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(47055, "creepE", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(47874, "secretWallWithLock", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(49127, "skillPointOrb", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(51496, "springCreep", SerializedBooleanUberState, false)
DEFINE_STATE(52684, SerializedBooleanUberState, false)  // enemyDoor
DEFINE_NAMED_STATE(53374, "spiritShardPickup", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(53543, "drillZone", SerializedBooleanUberState, false)
DEFINE_STATE(54405, SerializedBooleanUberState, false)  // snowPileA
DEFINE_NAMED_STATE(54578, "fourSlotDoor", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(58058, "minesBreakableWall", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(58116, "creepB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(60202, "creepA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(60454, "creepDoorE", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(62800, "lagoonBreakableWall", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(62962, "twoSlotDoor", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(63056, "swampBreakableWall", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(64001, "largeExpOrb", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(64961, "smallExpOrb", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(65139, "willowsEndSecretWall", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(65172, "xpOrbB", SerializedBooleanUberState, false)

#undef GROUP_ID
#undef GROUP_NAME
#define GROUP_ID 28287
#define GROUP_NAME "winterForestGroupDescriptor"
DEFINE_NAMED_STATE(3938, "breakableFloorB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(6764, "springBlossomTimelinePlayed", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(10460, "boxA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(11124, "breakableFloor", SerializedBooleanUberState, false)
DEFINE_STATE(12866, SerializedBooleanUberState, false)  // mediumExpA
DEFINE_NAMED_STATE(13168, "breakableRocksA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(15252, "mediumExpC", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(16339, "thawStateDescriptor", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(22713, "pressurePlatePuzzleSolved", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(24327, "breakableWallA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(26844, "breakableFloorA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(28525, "mediumExpB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(30157, "secretWallThaw", SerializedBooleanUberState, false)
DEFINE_STATE(32414, SerializedBooleanUberState, false)  // mediumExpA
DEFINE_NAMED_STATE(40607, "hammerWall", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(43506, "breakableWallC", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(51721, "breakableWallB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(52043, "boxB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(55131, "leafPileA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(55482, "spiritShardA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(57792, "stompableFloor", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(61490, "leafPileB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(62332, "breakableRocksB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(64528, "savePedestalUberState", SavePedestalUberState, false)

#undef GROUP_ID
#undef GROUP_NAME
#define GROUP_ID 28895
#define GROUP_NAME "baursReachGroup"
DEFINE_STATE(1053, SerializedBooleanUberState, false)  // keystoneB
DEFINE_NAMED_STATE(2108, "powlTeaseTriggered", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(2129, "largeExpOrb", SerializedBooleanUberState, false)
DEFINE_STATE(2462, SerializedBooleanUberState, false)  // xpOrbA
DEFINE_STATE(2896, SerializedBooleanUberState, false)  // stompableFloorA
DEFINE_STATE(2931, SerializedBooleanUberState, false)  // breakableWallB
DEFINE_STATE(3777, SerializedBooleanUberState, false)  // mediumExpOrb
DEFINE_NAMED_STATE(4290, "doorWithFourSlots", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(4301, "xpOrbF", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(7152, "frozenMokiInteracted", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(7597, "smallExpB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(7616, "breakableRocksA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(7703, "breakableRocksK", SerializedBooleanUberState, false)
DEFINE_STATE(8664, SerializedBooleanUberState, false)  // stompableFloorA
DEFINE_STATE(8834, SerializedBooleanUberState, false)  // xpOrbA
DEFINE_STATE(8934, SerializedBooleanUberState, false)  // breakableWallB
DEFINE_NAMED_STATE(9321, "expOrbD", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(9613, "interactedWithTokkConditionC", ConditionUberState, false)
DEFINE_STATE(9949, SerializedBooleanUberState, false)  // keystoneC
DEFINE_STATE(10823, SerializedBooleanUberState, false)  // keystoneC
DEFINE_NAMED_STATE(10840, "energyHalfCell", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(11936, "breakableRocksG", SerializedBooleanUberState, false)
DEFINE_STATE(12140, SerializedBooleanUberState, false)  // xpOrbA
DEFINE_NAMED_STATE(12170, "mokiNpcState", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(12312, "kindledFireCondition", ConditionUberState, true)
DEFINE_NAMED_STATE(13636, "interactedWithTokk", SerializedIntUberState, 0)
DEFINE_STATE(14264, SerializedBooleanUberState, false)  // breakableWallA
DEFINE_STATE(17510, SerializedBooleanUberState, false)  // breakableWallA
DEFINE_NAMED_STATE(17914, "afterMoraDeathRetalkPlayed", SerializedBooleanUberState, false)
DEFINE_STATE(18358, SerializedBooleanUberState, false)  // keystoneD
DEFINE_STATE(18910, SavePedestalUberState, false)  // savePedestalUberState
DEFINE_STATE(19041, SerializedBooleanUberState, false)  // breakableWallA
DEFINE_NAMED_STATE(19077, "expOrbE", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(19481, "mapIconGrenadeTreeVisibleCondition", ConditionUberState, true)
DEFINE_NAMED_STATE(20731, "breakableRockWall", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(22127, "stompableGroundA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(22171, "interactedWithTokkConditionB", ConditionUberState, false)
DEFINE_STATE(22382, SerializedBooleanUberState, false)  // keystoneA
DEFINE_NAMED_STATE(22695, "placedCoal", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(22758, "winterForestBonfire", SerializedBooleanUberState, false)
DEFINE_STATE(22761, SerializedBooleanUberState, false)  // mediumExpOrb
DEFINE_NAMED_STATE(22959, "expOrbC", SerializedBooleanUberState, false)
DEFINE_STATE(23605, SerializedBooleanUberState, false)  // xpOrbA
DEFINE_NAMED_STATE(23678, "breakableRocksH", SerializedBooleanUberState, false)
DEFINE_STATE(23795, SerializedBooleanUberState, false)  // gorlekOreA
DEFINE_NAMED_STATE(24510, "shouldMokiShowUp", ConditionUberState, false)
DEFINE_STATE(24533, SerializedBooleanUberState, false)  // smallXPOrbB
DEFINE_NAMED_STATE(25315, "afterKwolokDeathRetalkPlayed", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(25522, "wispRewardPickup", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(27476, "energyUpgrade", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(27568, "canTickleBaurCondition", ConditionUberState, false)
DEFINE_STATE(27787, SerializedBooleanUberState, false)  // firePedestalBooleanUberState
DEFINE_NAMED_STATE(28059, "seedPodBroken", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(29098, "baurNpcState", SerializedIntUberState, 0)
DEFINE_STATE(29898, SerializedBooleanUberState, false)  // keystoneA
DEFINE_NAMED_STATE(30189, "grenadeLanternsHint", SerializedBooleanUberState, false)
DEFINE_STATE(30566, SerializedBooleanUberState, false)  // firePedestalBooleanUberState
DEFINE_STATE(30794, SerializedBooleanUberState, false)  // breakableWall
DEFINE_NAMED_STATE(31575, "fallingBranch", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(31667, "talkedWithMoki", ConditionUberState, false)
DEFINE_NAMED_STATE(31825, "frozenMokiInteractedCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(32092, "areaTextZone", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(32340, "creepDoor", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(32443, "closingGate", SerializedBooleanUberState, false)
DEFINE_STATE(33337, SerializedBooleanUberState, false)  // xpOrbB
DEFINE_STATE(33846, SerializedBooleanUberState, false)  // xpOrbE
DEFINE_STATE(34098, SerializedBooleanUberState, false)  // breakableWall
DEFINE_NAMED_STATE(34461, "breakableRocksJ", SerializedBooleanUberState, false)
DEFINE_STATE(34534, SerializedBooleanUberState, false)  // healthCellA
DEFINE_STATE(35045, SerializedBooleanUberState, false)  // smallXPOrbB
DEFINE_NAMED_STATE(35436, "memoriesPlayedOut", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(35874, "hintZoneA", SerializedBooleanUberState, false)
DEFINE_STATE(36231, SerializedBooleanUberState, false)  // xpOrbC
DEFINE_NAMED_STATE(36378, "smallExpA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(36649, "secretWallA", SerializedBooleanUberState, false)
DEFINE_STATE(37287, SerializedBooleanUberState, false)  // grenadeSwitchA
DEFINE_STATE(37444, SerializedBooleanUberState, false)  // keystoneB
DEFINE_STATE(38049, SerializedBooleanUberState, false)  // xpOrbB
DEFINE_NAMED_STATE(38120, "breakableRocksE", SerializedBooleanUberState, false)
DEFINE_STATE(38143, SerializedBooleanUberState, false)  // xpOrbA
DEFINE_NAMED_STATE(38525, "breakableRocksF", SerializedBooleanUberState, false)
DEFINE_STATE(39291, SerializedBooleanUberState, false)  // gorlekOreA
DEFINE_STATE(40089, SerializedBooleanUberState, false)  // xpOrbB
DEFINE_STATE(40242, SerializedBooleanUberState, false)  // xpOrbC
DEFINE_STATE(40744, SerializedBooleanUberState, false)  // healthCellA
DEFINE_NAMED_STATE(41299, "afterAvalancheRetalkPlayed", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(41777, "hintZone", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(42209, "enemyArenaComplete", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(43977, "firePedestal", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(44276, "canPlayPowlBackstory", ConditionUberState, false)
DEFINE_STATE(45066, SerializedBooleanUberState, false)  // xpOrbE
DEFINE_NAMED_STATE(45337, "largeXPOrbA", SerializedBooleanUberState, false)
DEFINE_STATE(46293, SerializedBooleanUberState, true)  // firePedestalBooleanUberState
DEFINE_STATE(46404, SerializedBooleanUberState, false)  // xpOrbB
DEFINE_STATE(46711, SerializedBooleanUberState, false)  // xpOrbB
DEFINE_NAMED_STATE(46875, "breakableRocksI", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(47529, "orePlaceholder", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(48186, "creepA", SerializedBooleanUberState, false)
DEFINE_STATE(48757, SerializedBooleanUberState, false)  // grenadeSwitchA
DEFINE_NAMED_STATE(49329, "breakyBridge", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(49900, "keystoneGate", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(49997, "breakableRocksB", SerializedBooleanUberState, false)
DEFINE_STATE(50368, SerializedBooleanUberState, false)  // keystoneD
DEFINE_NAMED_STATE(51471, "blowableFlameB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(51853, "healthHalfContainer", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(52440, "kindledFire", SerializedBooleanUberState, true)
DEFINE_NAMED_STATE(53166, "seenLoremasterMenu", SerializedBooleanUberState, false)
DEFINE_STATE(53283, SerializedBooleanUberState, false)  // xpOrbC
DEFINE_STATE(54235, SavePedestalUberState, false)  // savePedestalUberState
DEFINE_STATE(54373, SerializedBooleanUberState, false)  // smallXPOrbA
DEFINE_STATE(55384, SerializedBooleanUberState, false)  // smallXPOrbA
DEFINE_NAMED_STATE(55841, "canPlayMemories", ConditionUberState, false)
DEFINE_STATE(56062, SerializedBooleanUberState, false)  // breakableWallA
DEFINE_NAMED_STATE(57743, "secretWallBaur", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(58337, "doorOpened", SerializedBooleanUberState, false)
DEFINE_STATE(58675, SerializedBooleanUberState, false)  // gorlekOreA
DEFINE_NAMED_STATE(58848, "expOrbA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(59276, "interactedWithTokkConditionA", ConditionUberState, true)
DEFINE_NAMED_STATE(59287, "talkedToSleepingBaur", SerializedBooleanUberState, false)
DEFINE_STATE(59394, SerializedBooleanUberState, false)  // grenadeSwitchA
DEFINE_NAMED_STATE(59955, "interactedWithCampfire", SerializedBooleanUberState, false)
DEFINE_STATE(61536, SerializedBooleanUberState, false)  // xpOrbA
DEFINE_STATE(61789, SerializedBooleanUberState, false)  // firePedestalBooleanUberState
DEFINE_NAMED_STATE(61852, "frozenMokiIceBroken", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(61896, "breakableRocksC", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(61976, "afterGoldenSeinRetalkPlayed", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(62198, "leverSetup", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(62643, "breakableRocksD", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(64226, "orePickup", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(64742, "blowableFlameA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(65235, "mediumExpA", SerializedBooleanUberState, false)

#undef GROUP_ID
#undef GROUP_NAME
#define GROUP_ID 31136
#define GROUP_NAME "weepingRidgeElevatorFightGroup"
DEFINE_NAMED_STATE(3441, "willowsEndGateOpened", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(42681, "mapIconChargeJumpVisibleCondition", ConditionUberState, true)
DEFINE_NAMED_STATE(59099, "areaText", SerializedBooleanUberState, false)

#undef GROUP_ID
#undef GROUP_NAME
#define GROUP_ID 33399
#define GROUP_NAME "achievementsGroup"
DEFINE_NAMED_STATE(1857, "allPickupsCollectedCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(17398, "enemiesKilledByHazards", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(17893, "spiritBladeCollected", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(28382, "gotHitBySpider", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(32867, "hasAllMapsCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(33550, "sideQuestsCompleatedCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(34522, "shardEverEquipped", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(36285, "spiritLightGainedCounter", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(37371, "poisonousWaterTouchedCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(41928, "energyContainersCounter", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(50709, "spiritLightEverSpent", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(52378, "healthContainersCounter", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(56511, "shrinesCompleatedCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(58955, "poisonousWaterTouched", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(61261, "collectablesCounter", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(62715, "allHubProjectsDoneCondition", ConditionUberState, false)

#undef GROUP_ID
#undef GROUP_NAME
#define GROUP_ID 34543
#define GROUP_NAME "gameStateGroup"
DEFINE_NAMED_STATE(559, "hasGameBeenFinishedWithoutShard", ConditionUberState, false)
DEFINE_NAMED_STATE(7218, "hasGameBeenFinishedOnHard", ConditionUberState, false)
DEFINE_NAMED_STATE(11226, "gameFinished", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(17336, "isGameDifficultyHard", ConditionUberState, false)
DEFINE_NAMED_STATE(22007, "isGameDifficultyNormal", ConditionUberState, true)
DEFINE_NAMED_STATE(30984, "gameDifficultyMode", SerializedIntUberState, 1)
DEFINE_NAMED_STATE(31301, "hasGameBeenFinishedWithoutSpiritLightSpent", ConditionUberState, false)
DEFINE_NAMED_STATE(33875, "isGameDifficultyEasy", ConditionUberState, false)
DEFINE_NAMED_STATE(47938, "hasGameBeenFinishedWithoutDying", ConditionUberState, false)
DEFINE_NAMED_STATE(57524, "hasGameBeenFinished", ConditionUberState, false)

#undef GROUP_ID
#undef GROUP_NAME
#define GROUP_ID 36153
#define GROUP_NAME "corruptedPeakGroup"
DEFINE_NAMED_STATE(2824, "spineStateB", SerializedBooleanUberState, true)
DEFINE_NAMED_STATE(3013, "gorlekOreA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(3662, "expOrbB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(5369, "weepingRidgeGetChargeJump", SerializedBooleanUberState, false)
DEFINE_STATE(5552, SerializedBooleanUberState, false)  // mediumExpA
DEFINE_NAMED_STATE(6682, "xpOrbA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(8434, "spineStateA", SerializedBooleanUberState, true)
DEFINE_NAMED_STATE(12077, "xpOrbB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(12457, "healthContainerA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(14400, "pressurePlatePuzzleA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(17818, "pressurePlatePuzzleB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(18750, "mediumExpOrbPlaceholder", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(18883, "breakableWallD", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(20307, "spineStateC", SerializedBooleanUberState, true)
DEFINE_NAMED_STATE(22461, "breakableRockB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(23584, "elevatorCompleteState", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(23902, "expOrbA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(25095, "corruptedPeakSecretWallB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(30728, "spellPickup", SerializedBooleanUberState, false)
DEFINE_STATE(36521, SerializedBooleanUberState, false)  // expOrb
DEFINE_NAMED_STATE(38970, "leverBool", BooleanUberState, false)
DEFINE_NAMED_STATE(42305, "spineStateD", SerializedBooleanUberState, true)
DEFINE_NAMED_STATE(42589, "expOrbC", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(43597, "savePedestalUberState", SavePedestalUberState, false)
DEFINE_NAMED_STATE(44835, "corruptedPeakSecretWallA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(47520, "breakableRockA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(48472, "stompableFloorA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(51042, "stomperStateB", SerializedBooleanUberState, false)
DEFINE_STATE(53032, SerializedBooleanUberState, false)  // expOrb
DEFINE_NAMED_STATE(55011, "stompableFloorC", SerializedBooleanUberState, false)
DEFINE_STATE(56157, SerializedBooleanUberState, false)  // mediumExpA
DEFINE_NAMED_STATE(57716, "stompableFloorB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(60795, "breakableWall", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(62883, "stomperStateA", SerializedBooleanUberState, false)

#undef GROUP_ID
#undef GROUP_NAME
#define GROUP_ID 37858
#define GROUP_NAME "waterMillStateGroupDescriptor"
DEFINE_NAMED_STATE(2615, "waterMillSecretWallADestroyedArt", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(2797, "smallExpOrb", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(3421, "hornbugBreakWall", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(3685, "shardSlotUpgrade", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(5107, "landOnAndSpawnOrbsARespawnTimer", SerializedFloatUberState, 0.0)
DEFINE_NAMED_STATE(6338, "dashDoor", SerializedBooleanUberState, false)
DEFINE_STATE(8344, SerializedBooleanUberState, false)  // mediumExpA
DEFINE_NAMED_STATE(8487, "rotatingEnemyArenaStates", SerializedIntUberState, 0)
DEFINE_STATE(8675, SerializedFloatUberState, 0.0)  // landOnAndSpawnOrbs
DEFINE_NAMED_STATE(9487, "exitDoorOpen", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(10720, "watermillEscapeState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(11418, "orePickupA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(11772, "waterMillBossRoomBarrierOpen", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(12379, "finishedWatermillEscape", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(13968, "displayedFlingHint", SerializedBooleanUberState, false)
DEFINE_STATE(15961, SerializedBooleanUberState, false)  // spiritShardA
DEFINE_NAMED_STATE(16604, "waterMillEntranceFallingDiscUberStateDescriptor", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(16611, "expOrbA", SerializedBooleanUberState, false)
DEFINE_STATE(17790, SerializedFloatUberState, 0.0)  // landOnAndSpawnOrbs
DEFINE_STATE(19347, SerializedBooleanUberState, false)  // mediumExpA
DEFINE_NAMED_STATE(19930, "investigateWatermillCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(21874, "waterMillSecretWallBDestroyed", SerializedBooleanUberState, false)
DEFINE_STATE(22107, SerializedBooleanUberState, false)  // mediumExpA
DEFINE_NAMED_STATE(22393, "startWatermillEscapeCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(22902, "healthPlantB", SerializedFloatUberState, 0.0)
DEFINE_NAMED_STATE(23225, "playedNaruGumoCutaway", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(23644, "waterMillEntranceDoorUberStateDescriptor", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(24680, "landOnAndSpawnOrbsA", SerializedFloatUberState, 0.0)
DEFINE_NAMED_STATE(25031, "rescuedOpher", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(25833, "healthContainerA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(26885, "waterMillVisited", SerializedBooleanUberState, false)
DEFINE_STATE(28311, SerializedFloatUberState, 0.0)  // landOnAndSpawnOrbs
DEFINE_NAMED_STATE(31104, "poleLowered", SerializedBooleanUberState, false)
DEFINE_STATE(31136, SerializedBooleanUberState, false)  // mediumExpA
DEFINE_NAMED_STATE(31187, "recedingWater", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(31584, "wheelsActivated", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(31962, "waterMillBEntranceTriggerUberStateDescriptor", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(31966, "doorWithTwoSlotsBooleanDescriptor", SerializedBooleanUberState, false)
DEFINE_STATE(32628, SerializedBooleanUberState, false)  // keystoneA
DEFINE_STATE(32932, SerializedBooleanUberState, false)  // gorlekOreA
DEFINE_STATE(33063, SerializedBooleanUberState, false)  // xpOrbA
DEFINE_STATE(33642, SerializedBooleanUberState, false)  // mediumExpB
DEFINE_NAMED_STATE(34433, "wheelLever", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(34619, "enemyDoor", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(34636, "rotatingEnemyArenaRotationStateController", SerializedIntUberState, 0)
DEFINE_STATE(34646, SerializedBooleanUberState, false)  // spiritShardA
DEFINE_NAMED_STATE(34846, "beforeEscapeCondition", ConditionUberState, true)
DEFINE_NAMED_STATE(36070, "rotationState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(36741, "watermillEscapeActiveCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(37323, "enemyDoorA", SerializedBooleanUberState, false)
DEFINE_STATE(38044, SerializedFloatUberState, 0.0)  // landOnAndSpawnOrbs
DEFINE_NAMED_STATE(39255, "canPlayWatermillIntro", ConditionUberState, true)
DEFINE_STATE(41380, SerializedBooleanUberState, false)  // mediumExpA
DEFINE_STATE(41911, SerializedBooleanUberState, false)  // mediumExpB
DEFINE_STATE(43893, SerializedBooleanUberState, false)  // keystoneA
DEFINE_STATE(44551, SerializedFloatUberState, 0.0)  // landOnAndSpawnOrbs
DEFINE_NAMED_STATE(45656, "xpOrbWater", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(45906, "smallExpA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(47533, "gorlekOraA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(48554, "landOnAndSpawnOrbsARespawnTimerB", SerializedFloatUberState, 0.0)
DEFINE_NAMED_STATE(48983, "mapIconGrappleTreeVisibleCondition", ConditionUberState, true)
DEFINE_NAMED_STATE(50064, "mediumExpC", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(50780, "watermillEntranceTalkedToOpher", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(50902, "wheelAActive", SerializedBooleanUberState, false)
DEFINE_STATE(52110, SerializedBooleanUberState, false)  // mediumExpB
DEFINE_NAMED_STATE(52129, "waterMillBossRoomWheelFelt", SerializedBooleanUberState, false)
DEFINE_STATE(54186, SerializedFloatUberState, 0.0)  // landOnAndSpawnOrbs
DEFINE_NAMED_STATE(54231, "hintZone", SerializedBooleanUberState, false)
DEFINE_STATE(55450, SerializedBooleanUberState, false)  // xpOrbA
DEFINE_NAMED_STATE(55499, "expOrbB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(56444, "xpOrb", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(57552, "energyVessel", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(57762, "healthPlant", SerializedFloatUberState, 0.0)
DEFINE_NAMED_STATE(58000, "arenaWheelsActivated", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(58220, "smallExpAArt", SerializedBooleanUberState, false)
DEFINE_STATE(58286, SerializedBooleanUberState, false)  // gorlekOreA
DEFINE_NAMED_STATE(58736, "waterMillSecretWallADestroyedArtB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(58846, "gorlekOreB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(58947, "shardSlotExpansion", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(58976, "canRescueOpher", ConditionUberState, false)
DEFINE_STATE(59022, SerializedBooleanUberState, false)  // mediumExpA
DEFINE_NAMED_STATE(60716, "wheelBActive", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(60777, "landOnAndSpawnOrbsB", SerializedFloatUberState, 0.0)
DEFINE_NAMED_STATE(61481, "waterMillSecretWallADestroyed", SerializedBooleanUberState, false)
DEFINE_STATE(61727, SerializedFloatUberState, 0.0)  // landOnAndSpawnOrbs
DEFINE_STATE(62404, SerializedFloatUberState, 0.0)  // landOnAndSpawnOrbs
DEFINE_NAMED_STATE(64055, "wheelsActivatedEntry", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(64086, "expOrb", SerializedBooleanUberState, false)
DEFINE_STATE(64961, SerializedBooleanUberState, false)  // spiritShardA
DEFINE_NAMED_STATE(65187, "lifeCellA", SerializedBooleanUberState, false)

#undef GROUP_ID
#undef GROUP_NAME
#define GROUP_ID 42171
#define GROUP_NAME "spiderBatTestGroup"
DEFINE_NAMED_STATE(14000, "roundOneDefeated", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(26771, "arenaDoorClosed", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(32228, "allRoundsDefeated", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(43227, "roundTwoDefeated", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(53383, "enemyArenaState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(56229, "roundThreeDefeated", SerializedBooleanUberState, false)

#undef GROUP_ID
#undef GROUP_NAME
#define GROUP_ID 42178
#define GROUP_NAME "hubUberStateGroup"
DEFINE_NAMED_STATE(38, "shardPurchaseCount", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(2543, "shardTraderMovedToHubCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(2654, "craftCutsceneState", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(2907, "hasLeashCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(3072, "hasCompletedBuilderProjectSpiritWell", ConditionUberState, false)
DEFINE_NAMED_STATE(3295, "leafPileB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(3957, "beautificationComplete", ConditionUberState, false)
DEFINE_NAMED_STATE(4125, "mediumExpD", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(4826, "allBuilderProjectsDoneCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(5331, "hasGrenadeSpellCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(5630, "leafPileC", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(5815, "stompableFloorEnterHub", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(6117, "mediumExpG", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(7528, "builderProjectShardShop", SerializedByteUberState, 0)
DEFINE_STATE(9319, SerializedBooleanUberState, false)  // woodCrateC
DEFINE_NAMED_STATE(9780, "mediumExpE", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(10035, "leafPileA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(13327, "hutBExpOrb", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(13543, "mapIconPowerTreeVisibleCondition", ConditionUberState, false)
DEFINE_STATE(14903, SerializedBooleanUberState, false)  // mediumExpA
DEFINE_NAMED_STATE(15068, "builderProjectBeautify", SerializedByteUberState, 0)
DEFINE_STATE(15685, SerializedBooleanUberState, false)  // woodCrateA
DEFINE_NAMED_STATE(15844, "allCratesBrokenCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(16254, "gardenerProjectFlowers", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(16586, "builderProjectOpenCave", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(16825, "builderProjectSpiritWell", SerializedByteUberState, 1)
DEFINE_NAMED_STATE(16924, "hasCompletedBuilderProjectOpenCave", ConditionUberState, false)
DEFINE_STATE(17158, SerializedBooleanUberState, false)  // woodCrateC
DEFINE_NAMED_STATE(17489, "smallExpE", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(17732, "drillableWallB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(18249, "mapIconKiiVisibleCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(18448, "mediumExpF", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(18751, "builderProjectRemoveThorns", SerializedByteUberState, 1)
DEFINE_NAMED_STATE(19692, "areaText", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(19911, "allGardenerProjectsDoneCondition", ConditionUberState, false)
DEFINE_STATE(21105, SerializedBooleanUberState, false)  // woodCrateE
DEFINE_NAMED_STATE(23125, "gorlekOreA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(23193, "hubSpritWellIconVisible", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(23607, "builderProjectHousesB", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(25637, "hasCompletedBuilderProjectHouses", ConditionUberState, false)
DEFINE_STATE(26189, SerializedBooleanUberState, false)  // woodCrateC
DEFINE_STATE(26365, SerializedBooleanUberState, false)  // woodCrateA
DEFINE_NAMED_STATE(26640, "hasChargeCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(27110, "gorlekOreB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(27777, "warpHintShowed", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(28511, "hasCompletedBuilderProjectRemoveThorns", ConditionUberState, false)
DEFINE_NAMED_STATE(29390, "allGardenerProjectsCount", CountUberState, 0)
DEFINE_NAMED_STATE(30206, "smallExpA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(30520, "hutDExpOrbB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(31795, "drillableWallA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(32777, "hasCompletedBuilderProjectHousesC", ConditionUberState, false)
DEFINE_NAMED_STATE(33011, "gardenerProjectGrapplePlants", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(35232, "smallExpD", SerializedBooleanUberState, false)
DEFINE_STATE(35855, SerializedBooleanUberState, false)  // woodCrateE
DEFINE_STATE(36085, SerializedBooleanUberState, false)  // mediumExpA
DEFINE_STATE(36464, SerializedBooleanUberState, false)  // woodCrateD
DEFINE_NAMED_STATE(36609, "fatherMokiGone", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(37028, "smallExpB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(38393, "gardenerProjectSpringPlants", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(38743, "mediumExpC", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(38905, "pyreA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(40006, "gardenerProjectTree", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(40448, "builderProjectHousesC", SerializedByteUberState, 0)
DEFINE_STATE(40609, SerializedBooleanUberState, false)  // mediumExpB
DEFINE_NAMED_STATE(42096, "savePedestal", SavePedestalUberState, false)
DEFINE_NAMED_STATE(42762, "smallExpH", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(44748, "smallExpG", SerializedBooleanUberState, false)
DEFINE_STATE(47152, SerializedBooleanUberState, false)  // woodCrateB
DEFINE_NAMED_STATE(47651, "gardenerProjectBashPlants", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(47838, "hasCompletedBuilderProjectBeautify", ConditionUberState, false)
DEFINE_STATE(50325, SerializedBooleanUberState, false)  // woodCrateA
DEFINE_NAMED_STATE(50418, "gromIntroSequencePlayed", SerializedBooleanUberState, false)
DEFINE_STATE(51080, SerializedBooleanUberState, false)  // woodCrateB
DEFINE_NAMED_STATE(51230, "builderProjectHouses", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(51468, "hutAExpOrb", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(51934, "hutEExpOrb", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(52003, "shardShopCompletedCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(52497, "hutDExpOrb", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(52786, "energyCellA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(53757, "hasCompletedBuilderProjectHousesB", ConditionUberState, false)
DEFINE_NAMED_STATE(56769, "hasCompletedBuilderProjectShardShop", ConditionUberState, false)
DEFINE_STATE(56980, SerializedBooleanUberState, false)  // woodCrateD
DEFINE_NAMED_STATE(57055, "fatherMokiPresentCondition", ConditionUberState, true)
DEFINE_NAMED_STATE(57455, "hutCExpOrb", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(57675, "largeExpA", SerializedBooleanUberState, false)
DEFINE_STATE(59623, SerializedBooleanUberState, false)  // mediumExpB
DEFINE_NAMED_STATE(60373, "allBuilderProjectsCount", CountUberState, 0)
DEFINE_NAMED_STATE(61304, "shardShopState", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(62510, "hubDiscoveredCondition", ConditionUberState, false)
DEFINE_STATE(63260, SerializedBooleanUberState, false)  // woodCrateB
DEFINE_NAMED_STATE(63404, "smallExpC", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(63819, "woodCrateF", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(63860, "shardTraderNotYetMovedToHubCondition", ConditionUberState, true)
DEFINE_NAMED_STATE(64583, "gardenerProjectGrass", SerializedByteUberState, 0)

#undef GROUP_ID
#undef GROUP_NAME
#define GROUP_ID 44310
#define GROUP_NAME "wellspringGladesGroup"
DEFINE_NAMED_STATE(125, "stompableFloorC", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(1647, "smallExpA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(9902, "shardSlotUpgrade", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(15689, "shardTraderState", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(17523, "lifeVesselB", SerializedBooleanUberState, false)
DEFINE_STATE(29043, SerializedBooleanUberState, false)  // lifeVesselA
DEFINE_STATE(36911, SerializedBooleanUberState, false)  // lifeVesselA
DEFINE_NAMED_STATE(47361, "blowableFlame", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(47723, "largeExpA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(47923, "mediumExpA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(55192, "stompableFloorA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(57009, "stompableFloorB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(58796, "shrineEnemyRoom", SerializedBooleanUberState, false)

#undef GROUP_ID
#undef GROUP_NAME
#define GROUP_ID 44964
#define GROUP_NAME "raceGroup"
DEFINE_NAMED_STATE(3798, "raceLeaderboardFilterState", SerializedIntUberState, 2)
DEFINE_NAMED_STATE(8328, "firstRaceUnlockedMessagePlayed", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(11512, "wellspringRace", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(12682, "wellspringRaceIcon", SerializedBooleanUberState, true)
DEFINE_NAMED_STATE(21276, "raceInProgressState", BooleanUberState, false)
DEFINE_NAMED_STATE(22703, "silentWoodlandRace", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(23661, "baursReachWindTunnelRace", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(25545, "kwolokDropRace", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(28552, "mouldwoodDepthsRace", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(30767, "desertRace", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(33045, "baursReachWindTunnelRaceIcon", SerializedBooleanUberState, true)
DEFINE_NAMED_STATE(34110, "silentWoodlandRaceIcon", SerializedBooleanUberState, true)
DEFINE_NAMED_STATE(38162, "desertRaceIcon", SerializedBooleanUberState, true)
DEFINE_NAMED_STATE(40578, "mouldwoodDepthsRaceIcon", SerializedBooleanUberState, true)
DEFINE_NAMED_STATE(45951, "inkwaterMarshRace", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(49208, "allRacesBeatenCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(50495, "inkwaterMarshRaceIcon", SerializedBooleanUberState, true)
DEFINE_NAMED_STATE(50634, "testRace", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(54686, "lumaPoolsRace", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(56533, "lumaPoolsRaceIcon", SerializedBooleanUberState, true)
DEFINE_NAMED_STATE(57356, "raceMusicShouldPlayCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(63031, "kwolokDropRaceIcon", SerializedBooleanUberState, true)

#undef GROUP_ID
#undef GROUP_NAME
#define GROUP_ID 46462
#define GROUP_NAME "kwoloksCavernThroneRoomGroup"
DEFINE_NAMED_STATE(3872, "mediumExpA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(9440, "spiritShardA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(10105, "interactedWithMourningMokiCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(20733, "interactedWithMourningMoki", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(20780, "smallExpA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(26623, "bombableDoor", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(29054, "largeExpA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(29869, "haveBashAndKwolokNotIntroducedCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(31447, "leafPileA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(31575, "questRewardOrb", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(34885, "bombableWallA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(37897, "gorlekOreA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(56958, "leafPileC", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(59806, "wispRewardPickup", SerializedBooleanUberState, false)

#undef GROUP_ID
#undef GROUP_NAME
#define GROUP_ID 48248
#define GROUP_NAME "npcsStateGroup"
DEFINE_NAMED_STATE(110, "treekeeperAPresentCondition", ConditionUberState, true)
DEFINE_NAMED_STATE(1289, "adventurerMokiHasItemCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(1350, "windtornRuinsWispTeaser", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(1557, "hasMapLumaPools", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(1590, "hasMapWellspring", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(2131, "tokkLagoonDialogState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(2253, "lupoEncounteredWeepingRidge", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(2285, "lupoEncounteredWellspringGlades", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(2973, "hasMapKwoloksHollowNotCondition", ConditionUberState, true)
DEFINE_NAMED_STATE(2998, "avalancheUnlockedReplayCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(3492, "treekeeperBRetalk", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(3638, "hasMapKwoloksHollow", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(3709, "opherAtDoorCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(3846, "stenchTease", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(3880, "braveMokiMapIconCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(4045, "hasMapWillowsEnd", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(4306, "lupoEncounteredWellspringAfterQuest", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(4372, "howlCompletedReplayCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(4510, "lupoWantsToTalkToYou", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(4822, "adventurerMokiMovedToHubCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(4956, "fisherMokiHasItemCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(5060, "tuleyMentionedSeed", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(5186, "gromMentionedOre", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(5269, "desertRuinsLoreWispE", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(5653, "spiderBossCompletedReplayCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(5982, "metOpherHubAfterWatermill", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(6097, "tuleyWantsToTalkToYouCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(6194, "twillenGaveRumor", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(6632, "treekeeperARetalkCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(6730, "interactedWindsweptWastesCondition", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(6778, "tokkWatermillDoorBPresent", ConditionUberState, false)
DEFINE_NAMED_STATE(6992, "lupoEncounteredSilentWoodlands", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(7056, "lupoEncounteredMouldwoodDepths", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(7160, "desertRuinsLoreWispA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(7321, "gromTalkedAboutBaur", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(7646, "gromGaveWarning", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(7795, "mapmakerShowShardsCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(8483, "mouldwoodMokiHasItemCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(8697, "watermillEscapeCompletedReplayCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(8985, "willowsEndSeirExitCutscene", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(9309, "petrifieldOwlBossCompletedReplayCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(9394, "metGrom", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(9750, "hasMapGorlekMines", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(10315, "canGiveMapstoneRumor", ConditionUberState, false)
DEFINE_NAMED_STATE(10337, "talkedInHub", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(10830, "hasMapBaursReachNotCondition", ConditionUberState, true)
DEFINE_NAMED_STATE(11223, "mouldwoodDepthWispTeaser", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(12260, "desertGorlekHasItemCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(12352, "lupoEncounteredBaursReach", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(12707, "tokkWantsToTalkKwoloksHollowEntrance", ConditionUberState, true)
DEFINE_NAMED_STATE(12799, "twillenHubDialogState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(12954, "opherHubSpawnCondition", ConditionUberState, true)
DEFINE_NAMED_STATE(13320, "desertRuinsLoreWispD", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(14064, "treeKeeperPresentCondition", ConditionUberState, true)
DEFINE_NAMED_STATE(14141, "twilenWantsToTalkToYouCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(14878, "interactedAfterWellOpened", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(14995, "hasMapWindtornRuins", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(15642, "tokkState", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(15656, "feedingGroundsReplayCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(15833, "desertRuinsLoreWispB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(16157, "lupoEncounteredWillowsEnd", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(16429, "tokkKwolokEntrancePresent", ConditionUberState, true)
DEFINE_NAMED_STATE(16484, "hasMapLumaPoolsNotCondition", ConditionUberState, true)
DEFINE_NAMED_STATE(16489, "fastTravelEnabledUberState", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(16961, "petrifieldOwlBossUnlockedReplayCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(17387, "kiiWantsToTalkToYouCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(17527, "treekeeperBRetalkCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(18218, "hasMapWindtornRuinsNotCondition", ConditionUberState, true)
DEFINE_NAMED_STATE(18425, "lumaPoolsWispSpotted", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(18458, "inkwaterWellQuest", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(18767, "hasMapInkwaterMarsh", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(19396, "mapmakerShowMapIconEnergyUberState", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(19551, "kiiWantsToTalkToYou", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(20300, "howlsOriginInteractedAfterWellOpenedCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(20460, "hasKeystoneQuestCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(21009, "lupoEncounteredWellspringValley", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(22121, "inDangerCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(22890, "metOpherLibrary", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(24328, "motayWantsToTalkToYou", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(24724, "canMournKu", ConditionUberState, false)
DEFINE_NAMED_STATE(25267, "twillenKwolokDialogState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(25410, "kwolokUnlockedReplayCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(25629, "tokkWantsToTalkToYou", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(26055, "hasMapWellspringGladesNotCondition", ConditionUberState, true)
DEFINE_NAMED_STATE(26627, "lupoEncounteredKwoloksHollow", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(26656, "startedKeystoneQuestCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(26696, "watermillCEntranceInteraction", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(27701, "lupoEncounteredGorlekMines", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(28327, "tuleyWantsToTalkToYou", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(28384, "frozenMokiFirstInteractionCondition", ConditionUberState, true)
DEFINE_NAMED_STATE(28534, "ShowCreepheartCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(28782, "windsweptWastesRuinsDoor", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(28826, "sandwormEscapeUnlockedReplayCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(28897, "childMokiDialogState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(29104, "weaponmasterInHub", ConditionUberState, true)
DEFINE_NAMED_STATE(29237, "lupoWantsToTalkToYouCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(29604, "hasMapBaursReach", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(30073, "gromTalkedAboutLagoon", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(30368, "tokkSwampPresent", ConditionUberState, true)
DEFINE_NAMED_STATE(31357, "interactedBeforeKwolokCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(32160, "wandererNeedleQuest", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(32188, "tuleyCanSeedIntroCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(32206, "opherWantsToTalkToYouCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(32478, "howlReplayCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(32549, "interactedKwoloksCavern", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(32918, "baurReachWispTease", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(33449, "tokkBaursPresent", ConditionUberState, true)
DEFINE_NAMED_STATE(33576, "frozenMokiHasItemCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(33981, "tokkKwolokDialogState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(34318, "lupoEncounteredWindsweptWastes", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(34756, "twillenMournedKu", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(34938, "tokkInteractedAfterDesertQuest", ConditionUberState, false)
DEFINE_NAMED_STATE(35651, "lupoEncounteredWindtornRuins", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(36215, "hornbugCompletedReplayCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(36369, "weaponMasterPresentInSpringIntroductionB", ConditionUberState, true)
DEFINE_NAMED_STATE(36841, "hasMapWellspringValleyNotCondition", ConditionUberState, true)
DEFINE_NAMED_STATE(36943, "tokkLagoonPresent", ConditionUberState, true)
DEFINE_NAMED_STATE(37121, "mapmakerShowEnergyCellsCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(37364, "mouldwoodDepthsWisptIntro", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(37450, "avalancheCompletedReplayCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(37481, "hasMapWeepingRidge", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(37606, "treekeeperARetalk", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(37755, "completedKeystoneQuestCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(38077, "ShowMapIconCreepheartUberState", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(40170, "lupoEncounteredUberState", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(40451, "baurReachWispIntro", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(41206, "lupoEncounteredBaursReachAfterThaw", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(41238, "laserBossCompletedReplayCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(41666, "mapmakerShowMapIconShardUberState", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(42425, "frozenMokiHasNoItemCondition", ConditionUberState, true)
DEFINE_NAMED_STATE(42510, "adventurerMokiHasNoItemCondition", ConditionUberState, true)
DEFINE_NAMED_STATE(42584, "tokkIntroduced", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(42865, "frozenMokiDialogState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(43186, "gromWantsToTalkToYouCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(43210, "hasBoughtAllMarkers", ConditionUberState, false)
DEFINE_NAMED_STATE(43860, "gromWantsToTalkToYou", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(44189, "memorialReplayCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(44446, "desertRuinsLoreWispF", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(44991, "willowCeremonyReplayCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(45538, "hasMapHowlsOrigin", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(45600, "willowsEndSeirIntro", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(45615, "normalDialogCondition", ConditionUberState, true)
DEFINE_NAMED_STATE(45664, "interactedBeforeMill", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(45751, "gromTalkedAboutDesert", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(45764, "epilogueUnlockedReplayCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(45850, "tokkWantsToTalkWellspringGladesHub", ConditionUberState, true)
DEFINE_NAMED_STATE(46471, "gromTalkedAboutMouldwoodGate", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(46745, "opherMentiodedWatermill", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(46863, "gromInteractedOnce", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(47156, "hornbugUnlockedReplayCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(47517, "hasMapWellspringValley", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(47546, "lupoEncounteredHowlsOrigin", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(47625, "iceFisherHasItemCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(47785, "feedingGroundsWispIntro", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(48144, "mournedKuState", ByteUberState, 0)
DEFINE_NAMED_STATE(48388, "tokkWantsToTalkBaursReachJ", ConditionUberState, true)
DEFINE_NAMED_STATE(48423, "hasMapMouldwoodDepths", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(48619, "lupoEncounteredInkwaterMarsh", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(49214, "hasMapInkwaterMarshNotCondition", ConditionUberState, true)
DEFINE_NAMED_STATE(49360, "hasMapWindsweptWastesNotCondition", ConditionUberState, true)
DEFINE_NAMED_STATE(50081, "fisherMokiHasNoItemCondition", ConditionUberState, true)
DEFINE_NAMED_STATE(50161, "motayWantsToTalkToYouCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(50248, "lagoonMokiNotMovedToHub", ConditionUberState, true)
DEFINE_NAMED_STATE(50351, "mouldwoodMokiHasNoItemCondition", ConditionUberState, true)
DEFINE_NAMED_STATE(50408, "interactedBeforeKwolok", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(50722, "tokkWantsToTalkWatermillEntrance", ConditionUberState, true)
DEFINE_NAMED_STATE(51005, "opherWantsToTalkToYou", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(51189, "tokkWantsToTalkHowlsOriginEntrance", ConditionUberState, false)
DEFINE_NAMED_STATE(51645, "marshKeystoneQuest", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(52065, "desertRuinsLoreWispC", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(53028, "metMotay", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(54586, "tokkHowlsOriginPresent", ConditionUberState, true)
DEFINE_NAMED_STATE(54624, "spiderBossUnlockedReplayCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(54647, "hasMapWellspringGlades", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(54806, "gromTalkedAboutWatermill", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(54962, "iceFisherDialogState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(55122, "metOpherHubBeforeWatermill", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(55448, "lagoonMokiMovedTohubCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(55617, "lupoEncounteredLumaPools", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(55867, "hasMapWellspringNotCondition", ConditionUberState, true)
DEFINE_NAMED_STATE(56448, "metOpherHub", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(57434, "kwolokCompletedReplayCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(57456, "petrifiedOwlAwakeningReplayCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(57674, "mouldwoodMokiDialogState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(57677, "hasMapWeepingRidgeNotCondition", ConditionUberState, true)
DEFINE_NAMED_STATE(57936, "tokkWatermillDoorAPresent", ConditionUberState, true)
DEFINE_NAMED_STATE(57987, "mapmakerShowMapIconHealthUberState", SerializedByteUberState, 0)
DEFINE_NAMED_STATE(58004, "watermillEscapeUnlockedReplayCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(58214, "tokkWantsToTalkGlobal", ConditionUberState, false)
DEFINE_NAMED_STATE(59315, "racerMokiHasItemCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(59363, "tokkDesertPresent", ConditionUberState, true)
DEFINE_NAMED_STATE(59393, "lupoIntroCondition", ConditionUberState, true)
DEFINE_NAMED_STATE(59657, "laserBossUnlockedReplayCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(60776, "tokkWantsToTalkWalljumpChallangeA", ConditionUberState, true)
DEFINE_NAMED_STATE(60805, "twilenWantsToTalkToYou", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(61146, "hasMapWindsweptWastes", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(61148, "braveMokiHasMovedToHub", ConditionUberState, false)
DEFINE_NAMED_STATE(61309, "hasMapHowlsOriginNotCondition", ConditionUberState, true)
DEFINE_NAMED_STATE(61819, "hasMapSilentWoodlands", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(61868, "lupoEncounteredWellspring", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(62324, "hasMapSilentWoodlandsNotCondition", ConditionUberState, true)
DEFINE_NAMED_STATE(62552, "firstVoice", BooleanUberState, false)
DEFINE_NAMED_STATE(62835, "lupoIntroState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(63643, "hasMapMouldwoodDepthsNoCondition", ConditionUberState, true)
DEFINE_NAMED_STATE(63687, "sandwormEscapeCompletedReplayCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(65308, "mapmakerShowHealthCellsCondition", ConditionUberState, false)
DEFINE_NAMED_STATE(65309, "hasMapGorlekMinesNotCondition", ConditionUberState, true)
DEFINE_NAMED_STATE(65458, "hasMapWillowsEndNotCondition", ConditionUberState, true)
DEFINE_NAMED_STATE(65525, "lockPermanently", ConditionUberState, false)

#undef GROUP_ID
#undef GROUP_NAME
#define GROUP_ID 53632
#define GROUP_NAME "wellspringGroupDescriptor"
DEFINE_NAMED_STATE(1911, "energyVesselA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(2522, "lanternAndCreepA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(3195, "pushBlockPuzzleA", SerializedBooleanUberState, false)
DEFINE_STATE(3382, SerializedBooleanUberState, false)  // secretWallB
DEFINE_STATE(3622, SerializedBooleanUberState, false)  // leafPileA
DEFINE_NAMED_STATE(6500, "mediumExpOrbPlaceholderG", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(6869, "energyVesselB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(9366, "secretWallC", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(10462, "gotCompassCondition", ConditionUberState, false)
DEFINE_STATE(12019, SerializedBooleanUberState, false)  // mediumExpA
DEFINE_STATE(14947, SavePedestalUberState, false)  // savePedestal
DEFINE_NAMED_STATE(17403, "lifeVesselA", SerializedBooleanUberState, false)
DEFINE_STATE(18181, SavePedestalUberState, false)  // savePedestalUberState
DEFINE_NAMED_STATE(21124, "orePickupA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(21790, "smallExpA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(22486, "wispSequencePlayed", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(25556, "orePickupB", SerializedBooleanUberState, false)
DEFINE_STATE(25817, SerializedBooleanUberState, false)  // secretWallA
DEFINE_NAMED_STATE(26178, "showDoorCutsceneState", SerializedByteUberState, 0)
DEFINE_STATE(32197, SerializedBooleanUberState, false)  // leafPileA
DEFINE_NAMED_STATE(32785, "expOrbG", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(33168, "spiritShard", SerializedBooleanUberState, false)
DEFINE_STATE(40587, SerializedBooleanUberState, false)  // secretWallB
DEFINE_NAMED_STATE(41227, "questItemCompass", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(42264, "mediumExpOrbPlaceholderF", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(47744, "noCompassCondition", ConditionUberState, true)
DEFINE_NAMED_STATE(51706, "mediumExpOrbPlaceholderE", SerializedBooleanUberState, false)
DEFINE_STATE(51735, SerializedBooleanUberState, false)  // secretWallA
DEFINE_STATE(53974, SavePedestalUberState, false)  // savePedestal
DEFINE_NAMED_STATE(54915, "xpOrbUberState", SerializedBooleanUberState, false)
DEFINE_STATE(56829, SerializedBooleanUberState, false)  // mediumExpA
DEFINE_STATE(58126, SerializedBooleanUberState, false)  // secretWallA
DEFINE_NAMED_STATE(61074, "rotatingWheel", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(61128, "spiritShardA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(62356, "mediumExpOrbPlaceholderC", SerializedBooleanUberState, false)
DEFINE_STATE(62781, SerializedBooleanUberState, false)  // secretWallA
DEFINE_STATE(63074, SavePedestalUberState, false)  // savePedestalUberState
DEFINE_STATE(64763, SerializedBooleanUberState, false)  // secretWallA

#undef GROUP_ID
#undef GROUP_NAME
#define GROUP_ID 54846
#define GROUP_NAME "prologueGroup"
DEFINE_NAMED_STATE(27125, "areaText", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(47904, "isTandemCondition", BooleanUberState, false)

#undef GROUP_ID
#undef GROUP_NAME
#define GROUP_ID 58674
#define GROUP_NAME "_petrifiedForestGroup"
DEFINE_STATE(193, SerializedBooleanUberState, false)  // xpOrbA
DEFINE_NAMED_STATE(374, "petrifiedOwlClothDefault", ConditionUberState, true)
DEFINE_STATE(595, SerializedBooleanUberState, false)  // expOrbA
DEFINE_STATE(780, SerializedBooleanUberState, false)  // keyStoneD
DEFINE_NAMED_STATE(902, "creepBlocker", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(1816, "keystoneDUberState", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(1965, "savePedestalA", SavePedestalUberState, false)
DEFINE_NAMED_STATE(2169, "keystoneBUberState", SerializedBooleanUberState, false)
DEFINE_STATE(2227, SerializedBooleanUberState, false)  // keyStoneA
DEFINE_STATE(2317, SerializedBooleanUberState, false)  // areaText
DEFINE_NAMED_STATE(2797, "stompableFloorA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(3577, "stompableFloorB", SerializedBooleanUberState, false)
DEFINE_STATE(5285, SerializedBooleanUberState, false)  // blowableFlameA
DEFINE_NAMED_STATE(6254, "canPlayMokiCleanWaterVignette", ConditionUberState, false)
DEFINE_STATE(6936, SerializedBooleanUberState, false)  // xpOrbUberState
DEFINE_STATE(7071, SavePedestalUberState, false)  // savePedestalUberState
DEFINE_NAMED_STATE(7636, "petrifiedOwlStalkSequenceCompleted", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(8487, "CollectibleXpA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(8810, "drillableWallA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(9239, "leafPileB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(9583, "energyContainerA", SerializedBooleanUberState, false)
DEFINE_STATE(9881, SerializedBooleanUberState, false)  // expOrbC
DEFINE_STATE(10029, SavePedestalUberState, false)  // savePedestalUberState
DEFINE_NAMED_STATE(10677, "narratorLineShownHowl", SerializedBooleanUberState, false)
DEFINE_STATE(10685, SerializedBooleanUberState, false)  // blowableFlameA
DEFINE_STATE(10877, SerializedBooleanUberState, false)  // leafPile
DEFINE_STATE(10997, SavePedestalUberState, false)  // savePedestalUberState
DEFINE_STATE(11221, SavePedestalUberState, false)  // savePedestalUberState
DEFINE_STATE(11400, SerializedBooleanUberState, false)  // stompableFloor
DEFINE_STATE(11736, SerializedBooleanUberState, false)  // keyStoneC
DEFINE_NAMED_STATE(14313, "hutDoorUnlocked", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(14404, "canPlayMokiFoulWaterVignette", ConditionUberState, true)
DEFINE_STATE(14539, SerializedBooleanUberState, false)  // powlVignettePlayed
DEFINE_NAMED_STATE(14590, "mediumPickupB", SerializedBooleanUberState, false)
DEFINE_STATE(14593, SerializedBooleanUberState, false)  // secretWallA
DEFINE_NAMED_STATE(14912, "displayedGlideHint", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(15269, "playedEpilogue", SerializedBooleanUberState, false)
DEFINE_STATE(17420, SerializedBooleanUberState, false)  // keyStoneB
DEFINE_NAMED_STATE(17742, "blowableFlame", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(17974, "smallPickupA", SerializedBooleanUberState, false)
DEFINE_STATE(18735, SerializedBooleanUberState, false)  // lifeCellUberState
DEFINE_NAMED_STATE(18924, "mediumPickupA", SerializedBooleanUberState, false)
DEFINE_STATE(19769, SerializedBooleanUberState, false)  // keyStoneB
DEFINE_STATE(20143, SerializedBooleanUberState, false)  // leafPile
DEFINE_STATE(20713, SerializedBooleanUberState, false)  // gorlekOreA
DEFINE_NAMED_STATE(20724, "boolean_gasBallBridge", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(20944, "keystoneCUberState", SerializedBooleanUberState, false)
DEFINE_STATE(20983, SerializedBooleanUberState, false)  // expOrbA
DEFINE_NAMED_STATE(21139, "leverGateA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(21385, "narratorLineShriekAttackShown", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(21500, "doorState", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(22056, "narratorLineShown", SerializedBooleanUberState, false)
DEFINE_STATE(22472, SerializedBooleanUberState, false)  // xpOrbA
DEFINE_STATE(22503, SerializedBooleanUberState, false)  // xpOrbUberState
DEFINE_STATE(23186, SerializedBooleanUberState, false)  // expOrbA
DEFINE_NAMED_STATE(24457, "lagoonBreakableFloor", SerializedBooleanUberState, false)
DEFINE_STATE(24911, SerializedBooleanUberState, false)  // xpOrbA
DEFINE_STATE(26274, SerializedBooleanUberState, false)  // gorlekOreA
DEFINE_NAMED_STATE(26282, "shardSlotA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(26639, "smallExpOrbA", SerializedBooleanUberState, false)
DEFINE_STATE(28710, SerializedBooleanUberState, false)  // gorlekOreA
DEFINE_NAMED_STATE(29035, "narrationPetrifiedOwlStalk", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(29265, "shardSlotUpgradePlaceholder", SerializedBooleanUberState, false)
DEFINE_STATE(29622, SerializedBooleanUberState, false)  // stompableFloor
DEFINE_NAMED_STATE(30377, "shardPickupA", SerializedBooleanUberState, false)
DEFINE_STATE(30897, SerializedBooleanUberState, false)  // areaText
DEFINE_STATE(30908, SerializedBooleanUberState, false)  // expOrbC
DEFINE_STATE(32369, SerializedBooleanUberState, false)  // powlVignettePlayed
DEFINE_STATE(32647, SerializedBooleanUberState, false)  // expOrbA
DEFINE_NAMED_STATE(32810, "chaseState", SerializedIntUberState, 0)
DEFINE_STATE(33893, SerializedBooleanUberState, false)  // expOrbD
DEFINE_NAMED_STATE(33965, "breakableWallA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(34799, "diggableWallA", SerializedBooleanUberState, false)
DEFINE_STATE(36061, SavePedestalUberState, false)  // savePedestalUberState
DEFINE_STATE(36199, SerializedBooleanUberState, false)  // expOrbB
DEFINE_NAMED_STATE(36832, "floatZoneState", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(36965, "featherVignettePlayed", SerializedBooleanUberState, false)
DEFINE_STATE(37006, SerializedBooleanUberState, false)  // expOrbB
DEFINE_STATE(37037, SerializedBooleanUberState, false)  // leafPile
DEFINE_STATE(37128, SerializedBooleanUberState, false)  // lifeCellUberState
DEFINE_NAMED_STATE(37636, "stompableFloorC", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(37811, "mokiCleanWaterVignetteTriggered", SerializedBooleanUberState, false)
DEFINE_STATE(37885, SerializedBooleanUberState, false)  // expOrb
DEFINE_NAMED_STATE(38285, "shardA", SerializedBooleanUberState, false)
DEFINE_STATE(39950, SerializedBooleanUberState, false)  // secretWallA
DEFINE_NAMED_STATE(40066, "boolean_skeletonBoneA", SerializedBooleanUberState, true)
DEFINE_STATE(40073, SerializedBooleanUberState, false)  // keyStoneD
DEFINE_NAMED_STATE(41644, "mokiFoulWaterVignetteTriggered", SerializedBooleanUberState, false)
DEFINE_STATE(42158, SerializedBooleanUberState, false)  // expOrbC
DEFINE_STATE(42531, SerializedBooleanUberState, false)  // keyStoneA
DEFINE_STATE(43033, SerializedBooleanUberState, false)  // keyStoneC
DEFINE_NAMED_STATE(44215, "keystoneAUberState", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(44324, "creepA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(44798, "petrifiedForestNewTransitionKuVignettePlayed", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(44864, "escapeRocks", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(45819, "petrifiedOwlClothState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(46069, "petrifiedOwlClothCalm", ConditionUberState, false)
DEFINE_NAMED_STATE(46547, "collapsingSkeletonA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(46628, "petrifiedOwlClothBreak", ConditionUberState, false)
DEFINE_NAMED_STATE(46980, "petrifiedForestNewTransitionOriVignettePlayed", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(47179, "setupDownB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(47751, "breakableGroundA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(48394, "creebBulb", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(49272, "creepBall", SerializedBooleanUberState, false)
DEFINE_STATE(49535, SerializedBooleanUberState, false)  // expOrbA
DEFINE_NAMED_STATE(50410, "boolean_skeletonBoneC", SerializedBooleanUberState, true)
DEFINE_NAMED_STATE(51501, "boolean_skeletonBoneB", SerializedBooleanUberState, true)
DEFINE_NAMED_STATE(51890, "shownHint", SerializedBooleanUberState, false)
DEFINE_STATE(52280, SerializedBooleanUberState, false)  // secretWallA
DEFINE_NAMED_STATE(52345, "patrifiedForestBreakableFloor", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(54516, "mediumPickupC", SerializedBooleanUberState, false)
DEFINE_STATE(54560, SerializedBooleanUberState, false)  // stompableFloor
DEFINE_NAMED_STATE(54686, "breakableWall", SerializedBooleanUberState, false)
DEFINE_STATE(55650, SerializedBooleanUberState, false)  // expOrbA
DEFINE_NAMED_STATE(56043, "enemyRoom", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(58268, "wispCutscenePlayed", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(58684, "shownFlapEnemyHint", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(59372, "xpOrbB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(59691, "CollectibleXPB", SerializedBooleanUberState, false)
DEFINE_STATE(59714, SerializedBooleanUberState, false)  // expOrbD
DEFINE_NAMED_STATE(61252, "skeletonState", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(61327, "setupDownA", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(61391, "stomableFloorB", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(61577, "breakableHiddenWall", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(61616, "petrifiedOwlState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(63837, "clothBroken", SerializedBooleanUberState, false)
DEFINE_STATE(64057, SerializedBooleanUberState, false)  // expOrbA
DEFINE_STATE(64484, SerializedBooleanUberState, false)  // expOrb
DEFINE_STATE(64690, SerializedBooleanUberState, false)  // secretWallA
DEFINE_NAMED_STATE(65519, "stomableFloorA", SerializedBooleanUberState, false)

#undef GROUP_ID
#undef GROUP_NAME
#define GROUP_ID 61306
#define GROUP_NAME "shrineGroup"
DEFINE_NAMED_STATE(2129, "shrineLaser", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(2239, "shrineProjectile", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(15758, "shrineCount", CountUberState, 0)
DEFINE_NAMED_STATE(18888, "shrineMouldwoodDepths", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(26590, "shrineHammer", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(40441, "shrinePortal", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(52344, "shrineTeleport", SerializedBooleanUberState, false)
DEFINE_NAMED_STATE(56122, "shrineOfFall", SerializedBooleanUberState, false)

#undef GROUP_ID
#undef GROUP_NAME
#define GROUP_ID 61314
#define GROUP_NAME "spiderGroupDescriptor"
DEFINE_NAMED_STATE(55764, "spiderlingsQuestUberState", SerializedIntUberState, 0)
DEFINE_NAMED_STATE(61458, "spiderNpcState", SerializedIntUberState, 0)

#undef GROUP_ID
#undef GROUP_NAME
#define GROUP_ID 63018
#define GROUP_NAME "testUberStateGroupDescriptor"
DEFINE_NAMED_STATE(22925, "floatUberStateDescriptor", SerializedFloatUberState, 0.0)
