#pragma once
#include <Modloader/interception_macros.h>
#include <Modloader/app/structs/PlayFabEvents_PlayFabResultEvent_1_PlayFab_ClientModels_AndroidDevicePushNotificationRegistrationResult_.h>
#include <Modloader/app/structs/AndroidDevicePushNotificationRegistrationResult.h>

namespace app::classes::PlayFab::Events::PlayFabEvents_PlayFabResultEvent_1_PlayFab_ClientModels_AndroidDevicePushNotificationRegistrationResult_ {
    IL2CPP_REGISTER_METHOD(0x00673B90, void, Invoke, (app::PlayFabEvents_PlayFabResultEvent_1_PlayFab_ClientModels_AndroidDevicePushNotificationRegistrationResult_ * this_ptr, app::AndroidDevicePushNotificationRegistrationResult* result))
    IL2CPP_REGISTER_METHODINFO(0x0471DA20, PlayFabEvents_PlayFabResultEvent_1_PlayFab_ClientModels_AndroidDevicePushNotificationRegistrationResult__Invoke__MethodInfo)
} // namespace app::classes::PlayFab::Events::PlayFabEvents_PlayFabResultEvent_1_PlayFab_ClientModels_AndroidDevicePushNotificationRegistrationResult_
