#pragma once
#include <Modloader/interception_macros.h>
#include <Modloader/app/structs/PlayFabEvents_PlayFabResultEvent_1_PlayFab_MultiplayerModels_RolloverContainerRegistryCredentialsResponse_.h>
#include <Modloader/app/structs/RolloverContainerRegistryCredentialsResponse.h>

namespace app::classes::PlayFab::Events::PlayFabEvents_PlayFabResultEvent_1_PlayFab_MultiplayerModels_RolloverContainerRegistryCredentialsResponse_ {
    IL2CPP_REGISTER_METHOD(0x00673B90, void, Invoke, (app::PlayFabEvents_PlayFabResultEvent_1_PlayFab_MultiplayerModels_RolloverContainerRegistryCredentialsResponse_ * this_ptr, app::RolloverContainerRegistryCredentialsResponse* result))
    IL2CPP_REGISTER_METHODINFO(0x04717B28, PlayFabEvents_PlayFabResultEvent_1_PlayFab_MultiplayerModels_RolloverContainerRegistryCredentialsResponse__Invoke__MethodInfo)
} // namespace app::classes::PlayFab::Events::PlayFabEvents_PlayFabResultEvent_1_PlayFab_MultiplayerModels_RolloverContainerRegistryCredentialsResponse_
