#include <Core/api/game/game.h>
#include <Core/api/scenes/scene_load.h>
#include <Modloader/app/methods/UnityEngine/Rigidbody.h>
#include <Modloader/il2cpp_helpers.h>
#include <Modloader/windows_api/console.h>


namespace {
    using namespace app::classes;

    std::optional<il2cpp::WeakGCRef<app::GameObject>> broken_plank_go_ref;
    common::Droppable::ptr_t on_update_handle = nullptr;

    [[maybe_unused]]
    auto on_scene_loaded = core::api::scenes::event_bus().on<core::api::scenes::events::SceneStateChanged>("lumaSwampTransitionA", [](const auto& event) {
        if (event.state == app::SceneState__Enum::Disabled) {
            on_update_handle = nullptr;
        }

        if (event.state != app::SceneState__Enum::Loaded) {
            return;
        }

        const auto scene_root_go = il2cpp::unity::get_game_object(event.scene->fields.SceneRoot);

        broken_plank_go_ref = il2cpp::WeakGCRef(
            il2cpp::unity::find_child(
                scene_root_go,
                std::vector<std::string>{
                    "physics",
                    "logWall",
                    "autogenerated",
                    "edge4",
                }
            )
        );

        on_update_handle = core::api::game::event_bus().on<core::api::game::events::FixedUpdate>([](auto) {
            if (!broken_plank_go_ref.has_value()) {
                on_update_handle = nullptr;
                return;
            }

            const auto broken_plank_go = **broken_plank_go_ref;

            if (!broken_plank_go.has_value()) {
                on_update_handle = nullptr;
                return;
            }

            const auto rotation = il2cpp::unity::get_local_rotation(*broken_plank_go);
            if (std::abs(rotation.x) > 0.1f) {
                il2cpp::unity::set_local_rotation(*broken_plank_go, {0.f, rotation.y, rotation.z});
            }
        });
    });
} // namespace
